### ISSUE TITLE
Mocking a nested Vuex store module

### ISSUE THREAD

**Issue by funct7** [vuejs/vue-test-utils#1726] opened 2020-10-27 07:01 UTC
### Subject of the issue

I can't seem to get the `mocks` option for `mount` to work when I have to use namespaced Vuex store modules like so:

Component:

```js
const { mapState } = createNamespacedHelpers('foo');

export default { 
	computed: {
		...mapState(['someList',]),
	},
}
```

Test code:

```js
const mocks = {
	$store: {
		modules: {
			foo: {
				state: {
					someList: [],
				},
				namespaced: true,
			},
		},
	},
};
```

### Expected behaviour

Namespaced Vuex module state is mapped to the component.

### Actual behaviour

The test fails without being able to create the component.
```
    TypeError: Cannot read property 'foo/' of undefined

      at getModuleByNamespace (../../.yarn/$$virtual/vuex-virtual-925b4d3b4f/0/cache/vuex-npm-3.5.1-ac0af37483-2.zip/node_modules/vuex/dist/vuex.common.js:1130:42)
```

**Comment by afontcu** [comment] 2020-10-28 14:32
You might want to [check out the docs](https://vue-test-utils.vuejs.org/guides/#testing-vuex-in-components), as you need to pass down a store and a Vue instance (through `localeVue`) to the `mount()` method.

**Comment by lmiller1990** [comment] 2020-10-28 22:41
I am not sure this will work -  I don't think Vuex is going to respect a mocked store from `$mocks`.

The general usage for `mocks` is to directly override something, eg if you did

```
export default {
  computed: {
    foo() { this.$store.state.bar } 
  }
}
```

You could do

```
mocks: {
  $store: { state:  { bar: '' } } 
}
```

As said above you may need a real store for this. You could just make a snapshot of your actual store for the tests, without importing the entire real store, though.

**Comment by funct7** [comment] 2020-10-28 23:41
Thanks for the reply guys.

I've already checked the mentioned docs, but like [some comments](https://github.com/vuejs/vue-test-utils/issues/551#issuecomment-391777665) I'd much prefer to use a mock if possible.

So I just want to confirm a few things:
1. Is it not possible to use a mocked store with modules at the moment? (Both replies say "may" or "might")
2. If so, do you guys have plans to support it?

**Comment by lmiller1990** [comment] 2020-10-29 03:20
I have never tried to do this, my instinct is no it won't work and nor should it - when you mock something, you are deciding *not* to use a real implementation, so merging the mocked state with a real Vuex store doesn't make a ton of sense. You are either mocking a dependency, which means you need to bring the entire implementation, or you aren't.

It sounds like your real goal is just to avoid using a Vuex store at all, and pre-populate `...mapState(['someList',])` with some specific value? If this is the case and you are using Jest, you could just mock your `createNamespacedHelpers` function:

```js
jest.mock('createNamespacedHelpers', () => ({ 
  mapState: /* some implementation */ 
}))
const { mapState } = createNamespacedHelpers('foo');
```

I am not really clear on what the implementation would look like, I don't know how `mapState` works off the top of my head.

That said, you will lose a *lot* of coverage if you decide to do this. If you delete `createNamespacedHelpers`, your tests will not warn you. An alternative would be making a small Vuex store:

```
const store = new Vuex.Store({
  state: {
    foo: {
      someList: ['some value']
    }
  }
})
```

Then you would have your pre-set state.

Hopefully one of these options helps.

**Comment by lmiller1990** [comment] 2020-10-30 04:16
Anyway, this is the intended behavior. Happy to help with getting your test working, but I will close this issue since there is action to be taken in the code base for it.

**Closed as completed by lmiller1990** 2020-10-30 04:16 UTC

**Comment by funct7** [comment] 2020-10-30 04:44
I was hoping that a naive mocked state (like having `$store.foo.bar` be compatible with using `mapState('foo', ...)`) would work, but I guess it doesn't.
I think mocking `createNamespacedHelpers` would be the best option. Or I could just use the real store like in the docs.
In any case, I wanted to make sure that the store mock doesn't work, so I don't have to keep trying something that's not working.

Thanks for the support.

**Comment by lmiller1990** [comment] 2020-10-30 05:44
Sure - both have trade-offs, my experience is making a real store is more annoying and time consuming, but also will give you more confidence and better coverage. Good luck!
