### ISSUE TITLE
wrapper.find(ComponentName) fails if run after a test for that specific component

### ISSUE THREAD

**Issue by mkopinsky** [vuejs/vue-test-utils#956] opened 2018-09-05 21:08 UTC
### Version
1.0.0-beta.24

### Reproduction link
[https://github.com/mkopinsky/vue-test-loading-order-issue](https://github.com/mkopinsky/vue-test-loading-order-issue)

### Steps to reproduce
```
git clone git@github.com:mkopinsky/vue-test-loading-order-issue.git
npm install
npm run test:passes # This runs Parent.test.js first, and passes
npm run test:fails # This runs Child.test.js first, and fails
```

### What is expected?
Test outcomes should not depend on the order the tests run

### What is actually happening?
If the test for the parent component is run before the test for the child component, everything is dandy.
If a test for the child component is run first, the test for the parent component fails with `Error: [vue-test-utils]: find did not return Component, cannot call find() on empty Wrapper` when I call wrapper.find(ChildComponent)

**Comment by eddyerburgh** [comment] 2018-09-08 06:15
Thank you for providing a good minimal reproduction.

The issue was a hangover from previous versions where we needed to remove cached constructors. Due to an internal change, this is no longer necessary, so I removed the code and added a test to make sure tests don't leak like this in the future. It will be released in the next beta version

**Comment by eddyerburgh** [comment] 2018-09-08 06:32
For a quick fix, create the wrapper in the test function:

```js
it('test', () => {
const wrapper = mount(Parent)
wrapper.find(Child)
})
```

**Closed as completed** 2018-09-08 06:33 UTC
Labels: bug

**Comment by mkopinsky** [comment] 2018-10-12 14:31
Any chance you could release another beta with this fix (and other recent fixes)?
