### ISSUE TITLE
setData of shallowMount(component,options) does not set data unless you run the test with --no-cache

### ISSUE THREAD

**Issue by harm-meijer** [vuejs/vue-test-utils#1428] opened 2020-02-04 16:03 UTC
### Version
1.0.0-beta.29

### Reproduction link
[https://github.com/harm-meijer/vue-test](https://github.com/harm-meijer/vue-test)

### Steps to reproduce
Run `yarn test:unit` and see the test fail, run `yarn test:unit --no-cache` and the test will pass.

### What is expected?
Not sure what to expect but a warning would be nice

### What is actually happening?
Have to add --no-cache to have setData work

**Comment by dobromir-hristov** [comment] 2020-02-04 16:17
Your assertion is wrong, `category` vs `categories`. 

Also I am pretty sure it works, as `--no-cache` has nothing to do with VTU.

**Comment by harm-meijer** [comment] 2020-02-04 16:21
@dobromir-hristov  Sorry, thought I pushed the failing test but didn't. I pushed it now.

**Comment by harm-meijer** [comment] 2020-02-04 16:27
I am working on a Mac Catalina 10.15.2 (19C57) using node v10.17.0, yarn 1.19.2 and npm 6.13.6 but run the commands with yarn.

**Comment by lmiller1990** [comment] 2020-02-08 05:54
I pulled this down, did `yarn` and `yarn test:unit` and it worked, test passes.

Potential race condition? Idk try:

```js
import { shallowMount } from "@vue/test-utils";
import HelloWorld from "@/components/HelloWorld/index.vue";

describe("HelloWorld/index.vue", () => {
  it("renders props.msg when passed", async () => {
    const msg = "new message";
    const wrapper = shallowMount(HelloWorld, {
      propsData: { msg }
    });
    expect(wrapper.text()).toMatch(msg);
    wrapper.setData({
      foo: "bar"
    });
    
    await wrapper.vm.$nextTick();
    
expect(wrapper.vm.foo).toBe("bar");
  });
});
```

PS I really do not recommend using `setData`, is there a specific use-case for using it? We are talking about depreciating it for Vue 3 integration, I'm trying to learn all use cases for `setData`.

**Comment by lmiller1990** [comment] 2020-02-13 12:07
going to close this one since I don't think it is a bug in VTU; the reproduction repo passes on my machine. if you can reproduce it and provide a repo that fails, I can reopen and look into it.

**Closed as completed by lmiller1990** 2020-02-13 12:07 UTC

**Comment by harm-meijer** [comment] 2020-02-14 08:42
@lmiller1990  Thank you for your time. I was not able to reproduce locally after rebooting. On circle ci the tests will fail without `--no-cache` so I added that just to make sure.
