### ISSUE TITLE
Couldn't test MutationObserver even using $nextTick

### ISSUE THREAD

**Issue by hamzanouali** [vuejs/vue-test-utils#976] opened 2018-09-22 21:20 UTC
### Version
1.0.0-beta.25

### Reproduction link
[https://jsfiddle.net/Hamza_Nouali_Tipazian/eywraw8t/389365/](https://jsfiddle.net/Hamza_Nouali_Tipazian/eywraw8t/389365/)

### Steps to reproduce
- Copy that project from jsfiddle to your computer in order to run unit tests.

- in your test, you have to test editing some DOM elements that uses my v-xmodel directive and assert that this directive is working perfectly with NOT-FORM elements (h1,span..etc) as same as v-model works with Form elements (input, textarea..etc).
----------------
 example: test that while writing some text to <span  v-xmodel=" ' title ' " contenteditable=" true "> the " title" property is changing too.

Try the demo in jsfiddle to understand how v-xmodel works, and what you need to test.

### What is expected?
my own directive (you find it in jsfiddle) v-xmodel works with NOT-FORM elements (h1,span..etc) as same as v-model with inputs

### What is actually happening?
**When writing tests:**

- focus the element (v-xmodel=" ' title ' ")
- write somthing using innerText e.g: ' Hello world '
- assert that ' title ' in our data equals to ' Hello world '

**Result:**

Fail:

title does not equal ' Hello world '.

**After using:**

wrapper.vm.$nextTick( ()=>{ /* expect code */ done() } );

**Result:**

Fail :

Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

---
I am using vue-test-utils with jest (jsdom)

my v-xmodel directive uses MutationObserver to watch any DOM changes.

Because " jsdom " does not support MutationObserver, I use this:
[ https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.7.22/MutationObserver.js ]

**[ Package.json ]**
-------------------------------

"dependencies": {

    "@fortawesome/fontawesome-free": "^5.3.1",

    "axios": "^0.18.0",

    "buefy": "^0.6.7",

    "quill": "^1.3.6",

    "slick-carousel": "^1.8.1",

    "vue": "^2.5.17",

    "vue-carousel": "^0.13.1",

    "vue-picture-input": "^2.1.6",

    "vue-quill-editor": "^3.0.6",

    "vue-router": "^3.0.1",

    "vuejs-datepicker": "^1.5.3",

    "vuex": "^3.0.1"

  },

  "devDependencies": {

    "@babel/polyfill": "^7.0.0",

    "@vue/cli-plugin-babel": "^3.0.1",

    "@vue/cli-plugin-unit-jest": "^3.0.1",

    "@vue/cli-service": "^3.0.1",

    "@vue/test-utils": "^1.0.0-beta.20",

    "babel-core": "^7.0.0-bridge.0",

    "babel-jest": "^23.6.0",

    "identity-obj-proxy": "^3.0.0",

    "jsdom": "12.0.0",

    "jsdom-global": "3.0.2",

    "moxios": "^0.4.0",

    "mutation-observer": "^1.0.3",

    "node-sass": "^4.9.0",

    "regenerator-runtime": "^0.12.1",

    "sass-loader": "^7.0.1",

    "vue-template-compiler": "^2.5.17"

  },

**Comment by eddyerburgh** [comment] 2018-09-23 04:37
Thanks for the bug report. Can you make a minimal reproduction with a test for me to debug. You can use the Vue Test Utils reproduction template on CodeSandbox as a starting point—https://codesandbox.io/s/m4qk02vjoy

**Comment by hamzanouali** [comment] 2018-09-23 09:32
> Thanks for the bug report. Can you make a minimal reproduction with a test for me to debug. You can use the Vue Test Utils reproduction template on CodeSandbox as a starting point—https://codesandbox.io/s/m4qk02vjoy

Try this and thank you so much for your time <3 :
https://codesandbox.io/s/vqkn9jwq5l

**Comment by eddyerburgh** [comment] 2018-09-23 13:24
There are a few issues here.

1. The MutationObserver shim relies on mutation events like `DOMCharacterDataModified` and `DOMNodeInserted`, which aren't supported by jsdom.
2. You aren't triggering a focus event in your test, which is needed to initialize the observation in v-xmodel.js.
3. You need to run tests with `attachToDocument` true, becuase you're using `document.querySelector`. By default, vue-test-utils does not attach the rendered DOM nodes to the document.
4. jsdom does not support `innerText`

Since none of these are @vue/test-utils related, I'm closing this issue.

**Closed as completed by eddyerburgh** 2018-09-23 13:24 UTC
Labels: need repro
