### ISSUE TITLE
[1.0.0-beta-9] wrapper.contains gives TypeError

### ISSUE THREAD

**Issue by emman27** [vuejs/vue-test-utils#305] opened 2017-12-27 10:31 UTC
Stack trace as below, works perfectly fine in beta-8.
```
    TypeError: Cannot convert undefined or null to object
        at Function.keys (<anonymous>)
      
      at vmCtorMatchesSelector (node_modules/vue-test-utils/dist/vue-test-utils.js:339:22)
      at node_modules/vue-test-utils/dist/vue-test-utils.js:370:9
          at Array.filter (<anonymous>)
      at findVueComponents (node_modules/vue-test-utils/dist/vue-test-utils.js:365:21)
      at find (node_modules/vue-test-utils/dist/vue-test-utils.js:752:12)
      at VueWrapper.contains (node_modules/vue-test-utils/dist/vue-test-utils.js:830:15)
      at Object.<anonymous> (myfile.spec.js:14:20)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

Replica code:
```
import { shallow } from 'vue-test-utils';
import Parent from '@/components/Parent;
import Child from '@/components/Child';

describe('something', () => {
  const wrapper = shallow(Parent);
  it('Should contain child', () => {
    expect(wrapper.contains(Child).toBe(true)
  })
})
```

**Comment by eddyerburgh** [comment] 2017-12-27 10:58
The code for contains and find changed a lot in beta.9. 

Can you post the code for the child and parent components?

**Comment by emman27** [comment] 2017-12-28 01:20
@eddyerburgh I've discovered the source of the bug. Components which don't export the name property no longer register in the contains method.

Since name is an optional property (See https://012.vuejs.org/api/options.html#name), I'd like to suggest that this be retained as a bug and fixed rather than closed.

```
// Parent.vue
<template>
  <div>
    <child />
  </div>
</template>

<script>
import Child from './Child'
export default {
  name: 'HelloWorld',
  components: {Child}
}
</script>
```

```
// Child.vue (failing)
<template>
  <div>
    I am child
  </div>
</template>

<script>
export default {}
</script>

<style>

</style>
```

```
// Child.vue (passing)
<template>
  <div>
    I am child
  </div>
</template>

<script>
export default {
  name: 'Child'
}
</script>

<style>

</style>
```

**Comment by eddyerburgh** [comment] 2017-12-28 10:03
This will be solved in beta.10, by adding a name property to registered components that don't have a name and are stubbed in `shallow`.

In beta.8 the only coded for way to match components was by using the name property, if you used a component as a selector without a name property vue-test-utils would throw an error.

In beta.9 `find`, `findAll`, `contains`, `is`, now uses a component constructor to match components, which means a component without a name property can be used as a selector. The problem is, this only works in `mount`.

In `shallow`, the constructor can't be used because we create new components to override the existing components. In beta.10, we'll add a name property to any stubbed component that doesn't have a name property. This isn't an ideal solution, since we're mutating the compiled component object. But I think it's fine for the moment. I can't see any problems with adding a name property to a component that doesn't already have one.

**Comment by eddyerburgh** [comment] 2018-01-12 06:23
@emman27 can you check beta.10 solved this issue?

**Comment by emman27** [comment] 2018-01-17 08:00
@eddyerburgh Seems to be good! I've migrated over to `@vue/test-utils` as well, I understand it's the same `beta-10`?

**Comment by eddyerburgh** [comment] 2018-01-17 08:12
Yep, it's the same 👍 

Thanks for getting back to me, closing now 😄

**Closed by eddyerburgh** 2018-01-17 08:12 UTC
Labels: bug
