### ISSUE TITLE
Refine package exports to fix Jest 28 out of box compatibility

### ISSUE THREAD

**Issue by riovir** [vuejs/vue-test-utils#1975] opened 2022-05-23 13:29 UTC
Currently, `@vue/test-utils` doesn't work with Jest v28 + JSDOM out of the box, requiring the following workaround to prevent trying to read the browser export where CJS is expected:

**jest.config.js**
```js
moduleNameMapper: {
	'^@vue/test-utils$': require.resolve('@vue/test-utils'),
},
```

### Cleanup

**What should be cleaned up or changed**:
Refine the package.json exports declarations for the browser to offer the ESM and CJS editions in case of import and require being used. To do so would allow the package to work out of the box with Jest v28 + jest-environment-jsdom

**Provide any links for context**:
- [Jest v28 changelog entry about respecting package exports](https://jestjs.io/docs/upgrading-to-jest28#packagejson-exports) -> See examples of problematic packages
- [Comment about a package missing the require export for browsers](https://github.com/microsoft/accessibility-insights-web/pull/5421#issuecomment-1109168149)

**Comment by lmiller1990** [comment] 2022-06-14 00:35
Yeah - this lib is quite old and pre-dates ESM as a thing. We should probably support it, now that it's more widely used. Care to make a PR?

**Comment by IlCallo** [comment] 2022-10-28 14:35
https://github.com/vuejs/vue-jest/issues/479#issuecomment-1295074840

An explanation about this problem, dunno if it's fixable on vue-test-utils side, using `customExportConditions` seems to be the official solution

**Comment by IlCallo** [comment] 2022-10-28 14:39
A possible solution could be to export a Jest config preset and use it to set everything correctly, but I guess that's more a problem for `vue-jest` than vue-test-utils

**Comment by renatodeleao** [comment] 2022-12-20 15:21
Just hit this one while migrating my app to `vue@3`. My initial thought was "maybe is something with @vue/compat" and only after some search, I've hit this issue + [SO thread](https://stackoverflow.com/a/72608494/2801012).

@IlCallo  I understand it's not a `@vue/test-utils` issue _per se_ (https://github.com/vuejs/vue-jest/issues/479#issuecomment-1295074840,) but a reference on the `migration guide` page could save time for less experienced users — by experience I mean google search skills, because I have experience and It would take me a lot of time until I suspected about `jest`, since it was working fine with vue@2 @vue/test-utils@1. (Btw thank you for the explanation 🙏 )

`@vue/test-utils` is is framework agnostic, but the [installation guides](https://test-utils.vuejs.org/installation/) + demo examples suggest `jest` and friends, so probably worths a mention in the Migration guides docs? I can make a PR if you agree @lmiller1990

**Comment by lmiller1990** [comment] 2022-12-21 01:28
PRs to make docs better are always a good idea :pray: 

Note this code base is for VTU v1 (Vue 2). You might want https://github.com/vuejs/test-utils for the Vue 3 version.

**Comment by renatodeleao** [comment] 2022-12-23 11:46
@lmiller1990 done https://github.com/vuejs/test-utils/pull/1923, feel free to edit and make the writing/formatting style more aligned with the rest of the docs. Cheers! ✌️

**Comment by lmiller1990** [comment] 2022-12-26 00:16
Closed in #1923

**Closed as completed by lmiller1990** 2022-12-26 00:16 UTC

**Comment by ebisbe** [comment] 2023-01-23 15:12
@lmiller1990 I'm not sure why you said 'closed' to an open issue

**Comment by lmiller1990** [comment] 2023-01-23 23:09
My mistake, is this still  a bug? I think it was fixed, I might have tagged the wrong issue.

**Comment by ebisbe** [comment] 2023-01-24 14:36
#1923 has a reproduction link but hasn't been reviewed by anyone. This one seems closed. What I didn't fully understand is the relation. Maybe you wanted to link a PR. I guess it's fine for now.
