### ISSUE TITLE
How to stub methods called inside mount hook

### ISSUE THREAD

**Issue by kleinjm** [vuejs/vue-test-utils#148] opened 2017-11-03 20:06 UTC
I'm running into an issue where I can't mock the method called in my `mounted()` hook and I'm assuming it has to do with the load order.
```js
const myMethod = sinon.stub();
wrapper.setMethods({ myMethod });
```
I've also tried
```js
    const myMethod = sinon.spy();

    wrapper = mount(ProfileSidebarIndex, {
      methods: { myMethod },
    });
```
and mocking `mounted` itself
```js
    const mounted = sinon.stub();

    wrapper = mount(ProfileSidebarIndex, {
      mounted
    });
```
Is there a way to do this?

**Comment by kleinjm** [comment] 2017-11-03 20:56
If it helps, I figured out how to do this without the test utils but then I don't have the wrapper so I'm still stuck here.
```
    const Constructor = Vue.extend(MyComponent);
    vm = new Constructor();
    sinon.stub(vm, 'myMethod');
    vm.$mount();
```

**Comment by eddyerburgh** [comment] 2017-11-03 21:00
You can pass a methods object:

wrapper = mount(ProfileSidebarIndex, {
    mewthods: { mounted }
});

**Comment by kleinjm** [comment] 2017-11-03 21:13
no luck. Looks like this still runs the `mounted` hook
```
    const mounted = sinon.stub();
    wrapper = mount(ProfileSidebarIndex, {
      methods: { mounted }
    });
```

**Comment by eddyerburgh** [comment] 2017-11-03 21:33
Do you want to stub the mounted hook, or a method that's called in a mounted hook?

There isn't currently a way to pass stubs to hooks.

**Comment by kleinjm** [comment] 2017-11-03 22:21
either would work. Can't seem to get stubbing the mounted hook working any of the ways discussed in this thread

**Comment by eddyerburgh** [comment] 2017-11-04 07:03
Can you post a minimal reproduction?

I can successfully stub methods by passing a methods object in the mount options.

**Comment by kleinjm** [comment] 2017-11-06 14:30
I too am able to stub a method by passing it to the mount options. However, when that method is used in `mounted()` on the vue instance, it is not stubbed. I'm assuming this is because `mount()` (from your library, not to be confused with `mounted()` from Vue) first creates the vue instance and `mounted()` gets called before stubbing can happen. Going along with my other examples here, my component has this within the script
```js
    mounted() {
      this.myMethod();
    },
    methods: {
      myMethod() {
        ...
      },
      ...
    },
```
So to reiterate, I think `mounted()` is called before subbing `myMethod` happens. Thanks for all the help so far, let me know if you're unable to see the same issue.

**Comment by wtho** [comment] 2017-11-09 17:01
I can confirm the observation made by @kleinjm:
```javascript
const TestComp = Vue.extend({
  mounted() {
    this.testMethod()
  },
  methods: {
    testMethod() {
      console.log('this is the original test method!')
    }
  }
})

describe.only('TestComp', () => {
  it('should call the original method', () => shallow(TestComp))
  it('should not call the original method', () => shallow(TestComp, { stubs: ['testMethod'] }))
})
```
This example will print `this is the original test method!` in both tests. Mocking is no workaround.

**Comment by wtho** [comment] 2017-11-09 18:07
To further the discussion about how to mock hooks: Not sure, if this is too hacky, but if we do
```javascript
const vm = new TestComp()
vm.$options.mounted = [() => console.log('this is the successful mock of mounted')]
```
before `vm.$mount()` gets called (so basically when the [attributes get applied](https://github.com/vuejs/vue-test-utils/blob/b3c12c44ff1bb9274db4e60de776b6e94d5239b9/src/lib/create-instance.js#L59) in `create-instance.js`), it would work to replace hooks. Either a second `stubs`/`mocks` object could be provided, or we go through the stubs and mocks before applying them, filter for hook method names and add them in this different way.

**Comment by eddyerburgh** [comment] 2017-11-09 18:25
I think that's a good solution @wtho 

Would you like to implement it with a test case like the example you posted

**Comment by wtho** [comment] 2017-11-09 19:16
@eddyerburgh yeah, I would like to try. Some points I have in mind/ran into:
* My approach was to just *override* the current array of all mocked lifecycle-functions, but I just learned that e. g. Vuex does add its own hooks in `beforeCreate`, so just removing all functions might be the wrong approach. On the other hand I do not have an idea yet how to identify and remove only the function the author intends to override...
* At the time, when `mounted` will be called, other mocked methods seem to not work (see initial problem of this issue)

**Comment by wtho** [comment] 2017-11-10 19:09
Made it work partially:
* A lifecycle method in the mock object is added to the lifecycle-hook array after mount
* If the component contains the lifecycle method, it will be removed before adding the mock
* works currently for
  * beforeMount
  * mounted
  * beforeUpdate
  * beforeDestroy
  * destroyed
* works not for
  * beforeCreate (mock installation happens too late)
  * created (mock installation happens too late)
  * updated (seems not to be called in the test)
  * activated  (seems not to be called in the test)
  * deactivated (seems not to be called in the test)

I will continue to work on it, but I do not know, how to trigger `updated`, `activated` and `deactivated` on the mounted component. Any suggestions? Also I am not sure if I can mock `beforeCreate` and `created` at all, would a PR still be accepted?

**Comment by eddyerburgh** [comment] 2017-11-10 19:43
Thanks for looking into this @wtho 😀

It seems I really dropped the ball. The `stubs` option is for components, not methods. It's expected behavior that the example you posted doesn't overwrite the console.log method.

You can make the test pass by add a methods object:

  mount(TestComp, { methods: {testMethod: () => {}} })
```js
describe.only('TestComp', () => {
  it('should not call the original method', () => shallow(TestComp, { methods: {testMethod: () => {}}  }))
})
```

Sorry, I should have seen this earlier.

## Lifecycle events

I think we should add support for mocking all lifecycle events, or none.

Even though this issues is called ability to mock lifecycle hooks, the problem was that @kleinjm couldn't stub a method inside `mount`. This is solved by passing a methods object with a method to override the method called in `mount`.

I'm renaming this issue. Stubbing lifecycle events should be a separate issue.

Sorry for the confusion.

**Comment by eddyerburgh** [comment] 2017-11-10 19:45
I'm closing this issue, as I'm able to solve the original problem with the code I posted. 

@wtho  If you still want to stub lifecycle events, please create a fresh issue

**Closed by eddyerburgh** 2017-11-10 19:45 UTC
Labels: discussion, feature request

**Comment by wtho** [comment] 2017-11-11 11:03
I agree, we got carried away it seems.

@eddyerburgh One more thing, you say you can mock the methods using the methods property in options. It works, but the methods property seems not to be documented, and I also could not find it in the source code. Can you link it maybe (might be interesting for the lifecycle-hook issue)?

Should I create an issue for the missing documentation as well?

I will analyse the lifecycle mocking a bit further regarding the beforeCreate / created hooks, If I will be successful, I will let you know.

**Comment by eddyerburgh** [comment] 2017-11-11 11:20
So the mount options comprise two things.

There are the options used by vue-test-utils like `stubs`, `mocks`, `context`. These get used by vue-test-utils. I've just added a method to extract these.

The options then get passed to the component, just like when you create a Vue instance:

```js
const vm = new Vue({
  store: store,
  methods: methods
})
```

`methods` is part of that option. It overrides the methods on the component.

We need some docs on this, but I don't think we should specify methods specifically.

**Comment by kleinjm** [comment] 2017-11-14 20:18
@wtho thanks for looking into this, I hope that stubbing hooks will be possible.

@eddyerburgh thanks a ton for the feedback. I figured out that stubbing is working, however, I need to `await wrapper.vm.$nextTick();`.

**Comment by begueradj** [comment] 2019-02-09 11:55
Do you remember how you succeeded to stub `mounted()` hook? @kellym

**Comment by begueradj** [comment] 2019-02-09 12:18
@eddyerburgh  How can I stub the `mounted()` lifecycle hook? 

I tried what you suggested: `mount(TestComp, { methods: {mounted: () => {}} })`

**Comment by GitRaymond** [comment] 2019-03-01 14:08
You could spy on the method like so:

`const spy = jest.spyOn(ComponentName.methods, 'methodName');`
`const wrapper = shallowMount(ComponentName, {`
   `         localVue,`
          `  router,`
`}`
       `expect(spy).toHaveBeenCalled();`

**Comment by arvins-wittymanager** [comment] 2019-04-18 05:13
Thanks @GitRaymond, this worked for me:
```
const spy = sinon.spy(Component.methods, 'componentMethod') // Called in `created` hook
const wrapper = createWrapper()
expect(spy).to.have.been.called
spy.restore()
```

**Comment by begueradj** [comment] 2019-04-18 10:26
In fact the solution above worked for me too

**Comment by dcshiman** [comment] 2019-05-28 16:11
if you are want to mock the component on used in vue router you can use 
```
import mockComponentName from '../components/ComponentName'
import App from '@/App.vue'
import flushPromises from 'flush-promises'

describe('Routing', () => {
  it('It mounts correctly', async () => {
    jest.mock('../components/ComponentName', () => {
      mockComponentName.mounted = () => {}
      return mockComponentName 
    })

    let router = await require('@/router').default
    const wrapper = mount(App, {
      router
    })

    router.push('path/propValue')
    await flushPromises()

    let comp = wrapper.find(mockProductDetail)
    expect(comp.exists()).toBe(true)
    expect(comp.props('propName')).toBe('propValue')
  })
})
```
useful when testing props pass to components via router

**Comment by wtho** [comment] 2019-05-28 20:39
@dcshiman this issue was never about mocking a whole component, only about mocking a single lifecycle hook inside a component (in this case mount)

**Comment by begueradj** [comment] 2019-12-29 13:50
I tried the solutions above and none worked for me. Is there an update for this ?
basically I have the same issue described above and I want to spy on a function which is called from the `mounted` hook

**Comment by begueradj** [comment] 2019-12-29 15:37
Sorry, what the maintainer mentioned above solves my problem, I just did a mistake. Thank you all for your contributions.

**Comment by begueradj** [comment] 2019-12-29 18:02
Hello @eddyerburgh 
When i do what you suggested above:
```javascript
mount(TestComp, { 
  methods: {
    testMethod: () => {}
  }
})
```
And try later to assert the method is called:
```javascript
expect(wrapper.vm.testMethod).toBeCalled()
```
I get this error message:

```
Received has type:  function
Received has value: [Function bound testMethod]
```
Why this happens or how to fix it ?

**Comment by JessicaSachs** [comment] 2019-12-30 02:55
@begueradj you want `testMethod` to be a jest spy (or sinon)

E.g.
```js
mount(TestComp, {
    methods: {
        testMethod: jest.fn()
    }
})
```

**Comment by begueradj** [comment] 2019-12-30 08:25
Indeed, that is what I ended up doing last night, and it works, thank you very much for the feedback. @JessicaSachs 
I wonder if you have a hint why I got the error above for the previous implementation I did ?

**Comment by PJEstrada** [comment] 2021-12-06 16:28
Does this still work now? I'm trying to use the `methods` key on the options for the shallow mount, but non-mocked method is still executed.

**Comment by developeryashraj** [comment] 2022-02-28 06:25
> You could spy on the method like so:
> 
> `const spy = jest.spyOn(ComponentName.methods, 'methodName');` `const wrapper = shallowMount(ComponentName, {` ` localVue,` ` router,` `}` `expect(spy).toHaveBeenCalled();`

It was not working for me but after some trials I found a solution. So for those who is still facing issue with above @GitRaymond 's suggestion.

If you mount/shallowMount inside `describe` rather in `it` like I was doing then **change**

```js
describe('Mounted Lifecycle', () => {
    const mockMethodOne = jest.spyOn(MyComponent.methods, 'methodOne');
    const mockMethodTwo = jest.spyOn(MyComponent.methods, 'methodTwo');

    const wrapper = shallowMount(MyComponent);

    it('Validate data and function call during mount', () => {
        expect(mockMethodOne).toHaveBeenCalled();
        expect(mockMethodTwo).toHaveBeenCalled();
    })
})
```
**into**
```js
describe('Mounted Lifecycle', () => {
    const mockMethodOne = jest.spyOn(MyComponent.methods, 'methodOne');
    const mockMethodTwo = jest.spyOn(MyComponent.methods, 'methodTwo');

    it('Validate data and function call during mount', () => {
        const wrapper = shallowMount(MyComponent);

        expect(mockMethodOne).toHaveBeenCalled();
        expect(mockMethodTwo).toHaveBeenCalled();
    })
})
```

I normally prefer to put `shalloMount` outside `it` if there are multiple test that needs only one mounting. So if you are using multiple `describe` blocks and you are mounting component in each of them based on your need then above test case (_where mounting is outside `it`_) might not work even if you do `fdescribe` to run that specific block only. I tried other ways but for me it only worked when I moved that `shallowMount` inside `it`. Hope this helps !

**Note :-** Avoid using `methods` with `mount/shallowMount` or `setMethods` after mount as it's [deprecated](https://v1.test-utils.vuejs.org/api/wrapper/#setmethods).
