### ISSUE TITLE
new slot syntax template can't be accessed in shallowMount

### ISSUE THREAD

**Issue by manonrichou** [vuejs/vue-test-utils#1261] opened 2019-06-19 14:53 UTC
### Version
1.0.0-beta.29

### Reproduction link
[https://codesandbox.io/embed/vue-template-dr6i7?fontsize=14&previewwindow=tests](https://codesandbox.io/embed/vue-template-dr6i7?fontsize=14&previewwindow=tests)

### Steps to reproduce
Run the two tests in the link. The one pointing to the old syntax's slot will pass, the one pointing to the new slot's syntax won't. 

### What is expected?
Template with v-slot syntax can be accessed in the test when using shallow mount.

### What is actually happening?
The test pointing to the template using the new slot syntax fails, whereas the one with the  soon-to-be deprecated syntax passes.

**Comment by runarberg** [comment] 2019-08-02 21:03
Are there any workarounds (other then using the deprecated syntax)?

**Comment by kspackman** [comment] 2019-09-17 16:12
Very interested in this issue, so that we can upgrade our syntax and still be able to test our components.

**Comment by Stoom** [comment] 2019-11-11 12:30
> Are there any workarounds (other then using the deprecated syntax)?

What I've found is you need to provide your own stub for the component with slots.  If you do that and add the named slots you care about then they will render in the shallowMount.

```typescript
wrapper = shallowMount(Appbar, {
    store, router, localVue, vuetify, stubs: {
        VTooltip: '<v-tooltip-stub><slot></slot><slot name="activator"></slot></v-tooltip-stub>',
    },
});
```

**Comment by runarberg** [comment] 2019-11-12 20:19
@Stoom That does not help if you need to test something that is inside a higher order component that uses scoped slots. E.g. in the following example, anything inside `<SomeHigherOrderComponent>` will be stubbed out:

```vue
<SomeHigherOrderComponent v-slot="scope">
  <p>
    We can use <code>scope</code> here,
    but <code>shallowMount</code> will stub this out.
    So we have to use <code>mount</code> to test it.
  </p>
</SomeHigherOrderComponent>

**Comment by runarberg** [comment] 2019-11-12 20:22
Perhaps this is relevant, but [vuese](https://github.com/vue-contrib/vuese) is experiencing a similar issue of not being able to access content inside slots that use the new `v-slot` syntax.

https://github.com/vue-contrib/vuese/issues/119

**Comment by Stoom** [comment] 2019-12-01 04:25
@runarberg When I was testing VHover from vuetify I just did the following and it worked enough for  me....

```typescript
        wrapper = shallowMount(Settings, {
            propsData, localVue, vuetify, store, stubs: {
                VHover: `<slot></slot>`,
            },
        });
```

**Comment by runarberg** [comment] 2019-12-10 21:57
@Stoom That doesn’t work for me. What I need to test is a child of the component using the `v-slot`:

```vue
<MyParent>
  <p>This is OK</p>

  <template v-slot="scope">
    <p>
      <strong>I need to test this.</strong>
      And I don’t know how to use <var>shallowMount</var>
      without it stubbing this out.
    </p>
  </template>
</MyParent>
```

Here `<MyParent>` has a slot scope on the default slot. I would need to stub the entire component to get it render, and then I might as well not write the unit test.

**Comment by lmiller1990** [comment] 2019-12-20 22:42
Good slot support is something we will address before moving from beta to 1.0 - I'll try my best to fix this in the near future.

**Comment by lmiller1990** [comment] 2019-12-22 02:48
Tried reproducing but failed to do so here: https://github.com/vuejs/vue-test-utils/pull/1383/files

I'll try pulling the reproduction repo.

**Comment by lmiller1990** [comment] 2019-12-23 00:29
Progress! I got it working in https://github.com/vuejs/vue-test-utils/pull/1383

Need to clean the code up and cover some edge cases (and support dynamic slots). Hopefully get this merged in soon!

**Comment by lmiller1990** [comment] 2020-01-09 12:55
Merged in... this will go out in beta-31.

**Comment by mtwolak** [comment] 2020-02-11 08:39
Why this issue has been closed? It seems issue has not been fixed, it still fails with provided link on version beta-31. Tests with new slot syntax in our production code also fails when updated to beta-31.

**Comment by lmiller1990** [comment] 2020-02-11 10:17
I thought this had been fixed - at least, we have unit tests merged in using the new `v-slot` syntax, [here](https://github.com/vuejs/vue-test-utils/blob/775feb78969007c992edb5a0406fd8658e1c167d/test/specs/shallow-mount.spec.js#L101).

You are right - the provided repo fails. This is the source component:

```js
<template>
  <Foo>
    <template v-slot:newSyntax>
      <p class="new-example">text not rendered</p>
    </template>
    <template slot="oldSyntax">
      <p class="old-example">text rendered</p>
    </template>
  </Foo>
</template>
```

This is the source test

```js
test("render old syntax slot", () => {
  const wrapper = shallowMount(App);
  expect(wrapper.find(Foo).exists()).toBe(true);
  expect(wrapper.find(".old-example").exists()).toBe(true);
});

test("render new syntax slot", () => {
  const wrapper = shallowMount(App);
  expect(wrapper.find(Foo).exists()).toBe(true);
  console.log(wrapper.html())
  expect(wrapper.find(".new-example").exists()).toBe(true);
});
```

Removing the template with `v-slot:newSyntax` lets the first test pass:

```js
<template>
  <Foo>
    <template slot="oldSyntax">
      <p class="old-example">text rendered</p>
    </template>
  </Foo>
</template>

// test
test("render old syntax slot", () => {
  const wrapper = shallowMount(App);
  expect(wrapper.find(Foo).exists()).toBe(true);
  expect(wrapper.find(".old-example").exists()).toBe(true);
});
```

And the same applies for the new syntax and new syntax test. I wonder if mixing the syntaxes is messing things up?

After thinking about this a bit more, does this even make sense? If we are using `shallowMount`...

```html
<template>
  <Foo>
    <template slot="oldSyntax">
      <p class="old-example">text rendered</p>
    </template>
  </Foo>
</template>
```

We are stubbing out `Foo` entirely - so shouldn't *none* on the content be rendered at all? Eg, should be:

```
<foo-stub></foo-stub
```

no?

@mtwolak can you provide a simple version of your failing production test? I am assuming you do not combine the new and old syntax.

**Comment by mtwolak** [comment] 2020-02-11 12:40
We're using vuetify v-tooltip: https://codesandbox.io/s/stoic-cookies-ovlv0. I didn't include vuetify library in codesand because of readability.
ShallowMount does not render component's child. I don't understand, why <span> with text is not rendered since it's not separate component.

**Comment by lmiller1990** [comment] 2020-02-11 21:26
I played with this and no luck. It could be related to Vuetify; it looks like it uses [requestAnimationFrame](https://github.com/vuetifyjs/vuetify/blob/f4b4f0aceeda667a2196f799d0a182bc6aea0fbb/packages/vuetify/src/components/VTooltip/VTooltip.ts#L160) and transitions to handle the tooltip, which are both things we have struggled with in the jsdom environment.

I'm surprised the first case with the old slot syntax works at all; that seems like a bug to me, in `shallowMount`. What do you think? Here's why I think it is a bug in `shallowMount`

`shallowMount` is supposed to stub out all child components. In your example:

```html
<template>
  <v-tooltip bottom>
    <template v-slot:activator="{ on }">
      <div v-on="on">
        <span class="grey--text">Text to be checked</span>
      </div>Some text for tooltip
    </template>
  </v-tooltip>
</template>
```

In this component (you called in `NewTooltip.vue` in your demo), child components in this markup are `v-tooltip`, so it should be stubbed to `v-tooltip-stub`. All the inner markup and lifecycle hooks are also stubbed. Why should the content of a stubbed child component render in `shallowMount` at all? This seems like the wrong behavior to me, from the start.

If you were mounting a `VTooltip`, then I would expect the inner markup to render. But you are mounting a `NewTooltip.vue`, so all components (including VTooltip) getting stubbed seems correct.

I am trying to figure out exactly what `shallowMount` should and should not do; everyone seems to have different expectations. Should it render the children here? Why? I'm guessing `mount` is not an option in your case.

**Comment by mtwolak** [comment] 2020-02-12 10:36
I thought only things from `components` will be stubbed in case of `shallowMount`. It's little suprising to me, because right now I will have to use `mount` on `tooltip` component, even if it's not using other components. But from the other hand, maybe it's expected (I don't know, I have small experience with Vue). Anyway, could you tell me, why `mount` is not an option in my case? I thought `mount` should render whole content (including template's content) but it seems it generated the same content as `shallowMount` did.

**Comment by lmiller1990** [comment] 2020-02-12 23:43
`mount` is an option - `mount` is always and option (and likely should be your go-to method).

The idea of `shallowMount` is to stub out all other components (not render their HTML, or run any of their JS code) to test your current one "in isolation". Turns out this probably wasn't a great design decision, it's confusing to a lot of users, so we are thinking of a better alternative(s) for v1 (and Vue 3 compat).

You should be able to use `mount` find, I believe. Can you try that and let me know how it goes? Vuetify still has a lot of edge cases, relating to `requestAnimationFrame`, so if you get some weird output post back here and I can help.

**Comment by mtwolak** [comment] 2020-02-13 13:34
It works with mount: https://codesandbox.io/s/gracious-satoshi-1zh8m.
Thank you very much for your support. Since `shallowMount` correctly stubs all its children this issue can be closed.

**Comment by mtwolak** [comment] 2020-02-13 14:21
However it seems it's strictly related to Vuetify, some of its components does not generate inner content anyway, for instance: https://codesandbox.io/s/gracious-satoshi-1zh8m

**Comment by lmiller1990** [comment] 2020-02-14 00:07
@mtwolak no bug, just looked it up - Vuetify's menu is closed by default. The test passes if you add a `:value="true"` prop:

```html
 <v-menu offset-y :value="true">
    <v-list>
      <v-list-item key="ab">
        <v-list-item-title>
          <span>This text should be displayed</span>
        </v-list-item-title>
      </v-list-item>
    </v-list>
  </v-menu>
```

Everything should work correctly using `mount`, since it just renders all the elements like a regular browser.

Did you find any other problems with Vuetify and mount?

**Comment by mtwolak** [comment] 2020-02-17 07:32
@lmiller1990 everything works as expected. I tried with more complex templates and adding value set to true resolves all problems. Thanks for help, completely missed out property "value" - I was searching for property called "visible" or "expand" or sth like that and it turned out value was exactly what I was searching for.

This issue should be closed, everything is correctly rendered.

**Closed as completed** 2020-02-17 08:00 UTC
Labels: bug
