### ISSUE TITLE
Vue + Jest + Typescript Unexpected reserved word 'let' and Jest encountered an unexpected token

### ISSUE THREAD

**Issue by Maniumn** [vuejs/vue-test-utils#1358] opened 2019-11-28 10:41 UTC
I get different errors by unit test for working code. With babel installed "Unexpected reserved word 'let'" and without babel installed "Jest encountered an unexpected token". What do I do wrong?

### Version
1.0.0-beta.29

### Reproduction links
[https://github.com/Maniumn/vue-typescript-babel-unit-test](https://github.com/Maniumn/vue-typescript-babel-unit-test)
[https://github.com/Maniumn/vue-typescript-no-babel-unit-test](https://github.com/Maniumn/vue-typescript-no-babel-unit-test)

### Steps to reproduce
git clone
npm i
npm run test:unit

### What is expected?
Test passed

### What is actually happening?
Errors: Unexpected reserved word 'let' and Jest encountered an unexpected token

**Comment by lmiller1990** [comment] 2019-12-14 23:24
This works out of the box for me:

<img width="539" alt="image" src="https://user-images.githubusercontent.com/19196536/70855809-b128ae00-1f1c-11ea-8f2d-95723acdf286.png">

Oh, I see you are using class component... let me try that now.

**Comment by lmiller1990** [comment] 2019-12-14 23:32
Ok, I got a similar error (but not about `let`) when using class component.

```
get setImages(): boolean {
    let x: number = 4
    let y = <number>x
    return true
  }
```

This seems to be the problem, specifically `let y = <number>x`. Try either:

- `let y = 4`
- `let y: number = x`
- `let y = x as number`

And it should be okay. It seemed to think `<` was the start of a JSX element. Here is the error I got:

```
 FAIL  tests/unit/example.spec.ts
  ● Test suite failed to run

    SyntaxError: /Users/lachlan/code/dump/testing-ts-utils/unknown: Expected corresponding JSX closing tag for <number> (11:8)

       9 |
      10 | }
    > 11 |         </>;
         |         ^
      12 |     }
      13 | };
      14 | tslib_1.__decorate([
```

I don't think it's a bug in vue-test-utils.

**Comment by lmiller1990** [comment] 2019-12-16 10:13
Going to close this one for now - let me know if you disagree with this, @Maniumn . If it helps, there is a tslint rule to prevent using `<type>` to cast a type, and use the `as type` syntax instead.

**Closed as completed by lmiller1990** 2019-12-16 10:13 UTC

**Comment by Maniumn** [comment] 2019-12-19 14:01
This is not a solution. My example is a little code from big project. In my project there are everywhere problems with test, let, JSX, babel ... Something is complettly wrong with vue class based and tests with jest.

**Comment by lmiller1990** [comment] 2019-12-19 23:10
@Maniumn , can you provide a repro demonstrating the problems with `let`? Your above reproduction does not use JSX, and the `let` problem was related to the `<` tag, used for typecasting.

I was able to get your reproduction running correctly by using the `as String` typecasting opposed to the `<string>` typecasting. You cannot use the `<string>` type with JSX - the parser does not know what to do when it encounters as `<` token.

If you have an alternative failing repro I can pull down, I'm happy to reopen this issue until we have a fix. "Something is completely wrong with class based tests with Jest" is not enough to allow me to troubleshoot your issue.

**Comment by vegerot** [comment] 2020-08-05 16:39
This is a problem plaguing me as well

**Comment by vegerot** [comment] 2020-08-05 16:48
@lmiller1990 I'm not using jsx anywhere in my project, and I don't want to.  Whenever I run jest on code using `<type>` assertions I get 
<img width="934" alt="image" src="https://user-images.githubusercontent.com/5297725/89440462-a3c56b80-d719-11ea-819e-5fcaef500289.png">
.  I see that [jsx is enabled by default](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/babel-preset-app#jsx).  So when I change my babel config to say 
<img width="231" alt="image" src="https://user-images.githubusercontent.com/5297725/89440573-cf485600-d719-11ea-8200-e60b04007842.png">
, I now get 
<img width="946" alt="image" src="https://user-images.githubusercontent.com/5297725/89440653-eedf7e80-d719-11ea-986b-52e1637a99da.png">
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/5297725/89440670-f69f2300-d719-11ea-8c8a-778c13ec3cf5.png">
.

**Comment by vegerot** [comment] 2020-08-05 16:49
My question: is there any way to use Vue without ANY jsx at all, in such a way that I can use `<type>` assertions?  Or does `vue-test-utils` require jsx compatible code?

Thanks so much for your help

**Comment by lmiller1990** [comment] 2020-08-05 21:36
You are using Vue 2 (not Vue 3 right) + Vue CLI?

The obvious work-around is just to use `(window as any)` instead of `(<any>window)`. Disallowing `<....>` casts is pretty common among React projects for this same reason - it is difficult for the parse to know what to do.

**Comment by vegerot** [comment] 2020-08-05 22:19
Yeah, that is the obvious workaround I'll do if this doesn't get answered.  But I was wondering if I could totally disable React and jsx in the parser, so there is no ambiguity

**Comment by lmiller1990** [comment] 2020-08-06 01:31
Most likely it is possible to disable JSX, you will need to play around with the Vue CLI config. This is not really a VTU specific problem but Jest + tooling. There is likely some magic configuration that will allow this to work but for now I would recommend just never using the `<type>` type-casting syntax.

If I have some time I might try figure this out but I cannot promise I can spend time on this with other issues taking priority. Let me know if you do get it working, though, I am sure someone wants this.

**Comment by vegerot** [comment] 2020-08-13 19:00
Thank you.  The easy solution is simply to enable [eslint](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/consistent-type-assertions.md).  I have went through everything I could to get rid of all jsx references to no avail.  So I will use the eslint rule.  :(

**Comment by gopalakrishnanr-paypaycorp** [comment] 2021-03-25 12:03
> You are using Vue 2 (not Vue 3 right) + Vue CLI?
> 
> The obvious work-around is just to use `(window as any)` instead of `(<any>window)`. Disallowing `<....>` casts is pretty common among React projects for this same reason - it is difficult for the parse to know what to do.

Thanks @lmiller1990 its working.

In my case  `  lookupContainer: HTMLElement = <HTMLElement >this.$refs.lookupResult; `

Change to  `  lookupContainer: HTMLElement = this.$refs.lookupResult as any; `

**Comment by vegerot** [comment] 2021-03-31 13:18
> In my case ` lookupContainer: HTMLElement = <HTMLElement >this.$refs.lookupResult;`
> 
> Change to ` lookupContainer: HTMLElement = this.$refs.lookupResult as any;`

Why not just do

```ts
lookupContainer: HTMLElement = this.$refs.lookupResult as HTMLElement;
```
?
