### ISSUE TITLE
Jest 22.x support

### ISSUE THREAD

**Issue by cristijora** [vuejs/vue-test-utils#369] opened 2018-01-21 19:25 UTC
### Version
1.0.0-beta.10

### Reproduction link
Do not have one yet

### Steps to reproduce
Upgrade to latest jest > 22.0.0
Try to select svg specific attributes by class
```js
wrapper.find('.some-class')
```
Where the wrapper contains `path` or `rect` elements

```html
<path class="some-class"></path>
```
or
```html
<rect class="some-class"></rec>
```

### What is expected?
Find method to return the selected elements

### What is actually happening?
Find returns no elements. Querying by tag
`find('path')` seems to work but it's more of a workaround

---
I also get a strange issue on a test but haven't isolated it yet to see where the problem actually is
```
TypeError: Cannot read property 'split' of undefined
      
      at getTransitionInfo (node_modules/vue/dist/vue.runtime.common.js:6840:58)
      at whenTransitionEnds (node_modules/vue/dist/vue.runtime.common.js:6810:13)
      at node_modules/vue/dist/vue.runtime.common.js:7037:11
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:592:19)
```

`getTransitionInfo` seems to use `getComputedStyles` which probably changed in the new jsdom version that the latest jest is using.

**Comment by eddyerburgh** [comment] 2018-01-25 20:53
Can someone create a reproduction in a GitHub repo?

**Comment by dannynicolas** [comment] 2018-01-29 18:23
I ran into a similar issue with SVG and based on my searching, it is a JSDOM / javascript issue with SVGs, not necessarily vue-test-utils or jest. I haven't looked into this since the early betas, so I'll take another look after updating to beta.11 

The workaround I did was to attach to document and look at the HTML to confirm that it actually rendered the svg.
eg.
```
test('the d3 svg chart renders with the component', () => {
    const wrapper = mount(D3Chart, {
      attachToDocument: true,
    });
    expect(wrapper.html()).to.contain('svg');
  });
```

**Comment by cristijora** [comment] 2018-01-29 18:40
Reproduction repo https://github.com/cristijora/vue-test-utils-jest-example
Jest 21
- [x] Find `path` by class name
- [ ] Find by `path` by tag

Jest 22
- [ ] Find `path` by class name
- [x] Find `path` by tag
😆 

as @dannynicolas says, this is most likely a JSDOM issue since jest 22 uses a newer JSDOM version

**Comment by eddyerburgh** [comment] 2018-01-31 09:42
Thanks for the repro 😀

I looked into this, and I'm going to close this as a JSDOM issue—https://github.com/jsdom/jsdom/issues/2128

**Closed as completed by eddyerburgh** 2018-01-31 09:42 UTC
Labels: need repro

**Comment by Prior99** [comment] 2018-02-06 08:21
I cannot see how this can be closed with the related jsdom issue. This does not only affect SVGs but also transitions as mentioned above.

**Comment by cristijora** [comment] 2018-02-06 08:26
@Prior99  Indeed transitions are also affected but didn't dig too deep into it to get an exact answer why that happens.

**Comment by Prior99** [comment] 2018-02-06 08:31
@cristijora is it somehow possible to stub the transitions to have a working workaround except for downgrading to jest 21 until a fix in jsdom or vue-test-utils has been published?

**Comment by cristijora** [comment] 2018-02-06 12:25
@Prior99 I didn't spend too much time on that and left my deps to jest 21

**Comment by Prior99** [comment] 2018-07-04 07:43
Is there really nothing which can be done to work around this? The JSDOM issue has been open for over half a year now with no signs of being worked on. In the meantime projects using Vue need to stay 2 major versions of Jest behind.
