### ISSUE TITLE
Triggering event on elements inside a slot throws an exception

### ISSUE THREAD

**Issue by vlechemin** [vuejs/vue-test-utils#134] opened 2017-10-27 18:27 UTC
While trying to trigger an even inside a component's slot, we encounter an exception.
Please find part of the code below.

Component
```html
<template>
<div>
    <slot name="input">
    </slot>
</div>
</template>
```

Wrapper option
```js
{
    slots: {
        input: '<input />',
    },
}
```

Test
```js
wrapper.find("input").trigger("input")
```

The stack is not very useful
```
TypeError: Cannot read property '_withTask' of undefined
    at remove$2 ([...]/Input.spec.ts:11:346754)
    at updateListeners ([...]/Input.spec.ts:11:91651)
    at Array.updateDOMListeners ([...]/Input.spec.ts:11:347728)
    at patchVnode ([...]/Input.spec.ts:11:285527)
    at VueComponent.patch [as __patch__] ([...]/Input.spec.ts:11:297113)
    at VueComponent.Vue._update ([...]/Input.spec.ts:11:121921)
    at VueComponent.update ([...]/Input.spec.ts:11:1114851)
    at [...]/Input.spec.ts:11:1115051
    at Array.forEach (<anonymous>)
    at VueComponent.update ([...]/Input.spec.ts:11:1114931)
```

**Comment by eddyerburgh** [comment] 2017-10-29 16:08
Thanks for the bug report.

I can't reproduce this using the code you posted. Can you post a minimal reproduction?

**Comment by martinhummer** [comment] 2017-11-09 08:21
I get the same error, if i reference a method 'bar' which is not defined in the 'methods' object of the vue component.

Template
```html
<template>
<div>
<button id="foo" @click="bar">Edit</button>
<input type="text" />
</div>
</template>
```

If you try to do something like
```javascript
wrapper.find("input").trigger("input")
```
it will fail with the error message above.

**Comment by demsking** [comment] 2017-12-31 08:22
I got the same error using functional component and the render function.
After debugging, I saw that this occur when they are an an undefined event or an nullable event in the component:
```js
export default {
  functional: true,
  render (createElement) {
    return createElement('input', {
      on: {
        input: null,
        change: undefined
      }
    })
  }
}
```
Hope this will help to fix the issue

**Comment by johman10** [comment] 2018-01-25 08:10
I stumbled upon this issue as well, or at least something that looks like it. I found this problem with both the `wrapper.update` and `wrapper.trigger`.

I made a JSFiddle to demonstrate the issue here: https://jsfiddle.net/vyaceLhu/2/

Hope this helps and that someone can have a look into this. :)

**Comment by eddyerburgh** [comment] 2018-01-26 21:07
@johman10 The issue with the code you posted is that you aren't passing in any propsData: https://jsfiddle.net/eddyerburgh/d8739dkq/

I'm closing this issue since there isn't a reproduction we can use to fix the bug. If anyone has this problem in the future, please open an issue with the reproduction, it's very much appreciated!

**Closed by eddyerburgh** 2018-01-26 21:07 UTC
Labels: bug, help wanted
