### ISSUE TITLE
Warnings when running Jest Snapshot tests for components containing ElementUI table or dropdowns

### ISSUE THREAD

**Issue by chandrucrm** [vuejs/vue-test-utils#770] opened 2018-06-28 12:49 UTC
### Version
1.0.0-beta.20

### Reproduction link
[https://codesandbox.io/s/n9qkywmjvj](https://codesandbox.io/s/n9qkywmjvj)

### Steps to reproduce
Please download the project from Sandbox and run it locally to reproduce the issue(I don't know if sandbox will allow us to create snapshots)

However you can still see the warning in Problems tab of Sandbox

### What is expected?
Tests should succeed without any warnings

### What is actually happening?
Test succeeds but has below warnings
```

yarn run v1.7.0
$ npm run unit

> test-project@1.0.0 unit C:\Projects\Issues\vue-issue
> jest

 PASS  src\tests\Sample.spec.js
  Sample.vue
    √ displays default Sample (174ms)

  console.error node_modules\vue\dist\vue.runtime.common.js:589
    [Vue warn]: Error in callback for watcher "options": "TypeError: Cannot read property 'querySelectorAll' of undefined"

    found in

    ---> <ElSelect>
           <DropdownSample>
             <Root>

  console.error node_modules\vue\dist\vue.runtime.common.js:1739
    TypeError: Cannot read property 'querySelectorAll' of undefined
        at VueComponent.options (C:\Projects\Issues\vue-issue\node_modules\element-ui\lib\element-ui.common.js:8567:29)
        at Watcher.run (C:\Projects\Issues\vue-issue\node_modules\vue\dist\vue.runtime.common.js:3231:19)
        at flushSchedulerQueue (C:\Projects\Issues\vue-issue\node_modules\vue\dist\vue.runtime.common.js:2979:13)
        at Array.<anonymous> (C:\Projects\Issues\vue-issue\node_modules\vue\dist\vue.runtime.common.js:1835:12)
        at flushCallbacks (C:\Projects\Issues\vue-issue\node_modules\vue\dist\vue.runtime.common.js:1756:14)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

  console.error node_modules\vue\dist\vue.runtime.common.js:589
    [Vue warn]: Error in nextTick: "TypeError: Cannot read property 'clientWidth' of undefined"

  console.error node_modules\vue\dist\vue.runtime.common.js:1739
    TypeError: Cannot read property 'clientWidth' of undefined
        at TableLayout.updateColumnsWidth (C:\Projects\Issues\vue-issue\node_modules\element-ui\lib\element-ui.common.js:11450:36)
        at VueComponent.updateScrollY (C:\Projects\Issues\vue-issue\node_modules\element-ui\lib\element-ui.common.js:10269:19)
        at C:\Projects\Issues\vue-issue\node_modules\element-ui\lib\element-ui.common.js:10829:26
        at Array.<anonymous> (C:\Projects\Issues\vue-issue\node_modules\vue\dist\vue.runtime.common.js:1835:12)
        at flushCallbacks (C:\Projects\Issues\vue-issue\node_modules\vue\dist\vue.runtime.common.js:1756:14)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   1 passed, 1 total
Time:        3.167s
Ran all test suites.
Done in 5.80s.
```

**Comment by eddyerburgh** [comment] 2018-06-28 13:55
The issue is because you're trying to render an already mounted instance with renderToString. Instead you should use the wrapper.html method:

```js
wrapper.html()
```

Or use `@vue/server-test-utils` to render on the server:

```js
import { renderToString } from `@vue/server-test-utils`

// ...

const str = renderToString(TestComponent)
```

**Comment by chandrucrm** [comment] 2018-06-28 14:41
Thanks @eddyerburgh 

`wrapper.html()` does solve my issue.
@vue/server-test-utils still gives me the same warning.

I was wondering whether the issue is just rendering already mounted instance with renderToString() because the tests for other components did not give this warning.

I am happy with wrapper.html() solution but i am curious about this inconsistancy
I have updated the code in sandbox with another component which doesn't contain element-ui table or dropdown components. The test for this succeeds without any warning (Ignore the --updateSnapshot flag error)

New.vue
```
<template>
 <div>
 <el-row>
      <el-col :xs="24" :sm="24" :md="12" :lg="6" :xl="12">
        <el-input
          placeholder="Name"
          v-model="name"
          type="text"
          autofocus= "true"
          maxlength="20"/>
      </el-col>
    </el-row>
 </div>
</template>

<script>
export default {
  name: "new-component",
  data() {
    return {
      name: "Thank you Edd"
    };
  }
};
</script>

```

New.spec.js
```

import { mount, createLocalVue } from "@vue/test-utils";
import { createRenderer } from "vue-server-renderer";
import ElementUI from "element-ui";
import New from "./../components/New.vue";

let localVue = createLocalVue();
localVue.use(ElementUI);

describe("New.vue", () => {
  it("snapshot New", () => {
    const wrapper = mount(New, { sync: false, localVue });
    const renderer = createRenderer();
    renderer.renderToString(wrapper.vm, (err, str) => {
      expect(str).toMatchSnapshot();
    });
  });
});

```

Thanks once again

**Comment by mleg** [comment] 2018-07-10 11:05
ElementUI's dropdown renders each time with a new id.
So to get consistent snapshots you need to replace this dynamic value for something static after getting an html string and before putting it into snapshot.
I do it with such function:
```javascript
function replaceDropdownMenuId(htmlString) {
	return htmlString.replace(/"dropdown-menu-\d+"/g, '"dropdown-menu-595"')
}
```

**TIP**: If you've looked into a git diff of your snapshot you'd probably noticed the reason instantly.

**Comment by eddyerburgh** [comment] 2018-07-21 16:14
Thanks @mleg . I'm closing this issue since the original issue is resolved.

**Closed as completed by eddyerburgh** 2018-07-21 16:14 UTC
Labels: question
