### ISSUE TITLE
Find is not returning nested elements based on CSS selector

### ISSUE THREAD

**Issue by codebryo** [vuejs/vue-test-utils#1191] opened 2019-03-21 19:42 UTC
### Version
1.0.0-beta.29

### Reproduction link
[https://codesandbox.io/s/jv9qr113q5](https://codesandbox.io/s/jv9qr113q5)

### Steps to reproduce
Please switch to the console view
Currently, find does not work for me in almost any case that has to do with CSS selectors. Nested Components seem to work when used with `ref` or `name`, but simple CSS selectors fail.

### What is expected?
Wrapper should present the selected element as wrapper object that allows interacting with it.

### What is actually happening?
Wrapper returns an empty object

---
I was trying to manipulate a form. This was all working properly before, but stopped working after I tried to upgrade vue alongside vue-template-compiler and @vue/test-utils

**Comment by eddyerburgh** [comment] 2019-03-22 04:46
When I run the codesandbox each call to `find` is returning a Wrapper. Can you check it again?

If you're experiencing this in a larger project, there might be another bug. beta.29 switched how sync mode was implemented, which has led to some edge cases.

**Comment by codebryo** [comment] 2019-03-22 09:21
So where I really feel it is currently in a test suite that tries to go through a more complex flow. 
At one point what now happens is it tells me `cannot call trigger() on empty Wrapper`, what leads me down the path that `find` is not returning the elements in the way it did before. I now tried to revert to beta.25 and it now still happens. The only upgrade I made now is from Vue 2.5.17 to latest version  (2.6.10) and vue template compiler from 2.5.16 -> 2.5.17

Does the version of template compiler and vue affect the test-utils in an expected way?

**Comment by GreggOD** [comment] 2019-03-30 13:59
Hi,

I am currently having a discreprancy with `find` and `findAll`, neither are working:
```
let input = wrapper.find('input') // {selector: 'input'} <- what do i do with this?
input.element // undefined <- tried that

wrapper.findAll('input') // {}
```

@eddyerburgh it would be nice in your test documentation to add what the returned object structure is supposed to look like. With .mount() I have no clue whats available to me on that object because I cant see it, so I have dont know whats at my disposal to leverage in cases like this where `.find()` doesnt work.

Same goes for `.find()` its returning a flat object of `{selector: 'input'}`, i have no idea if there are hidden properties I can access or if that return is expect or if its a bug.

```
"@vue/cli-plugin-unit-jest": "3.4.x",
"babel-jest": "24.1.x",
```

**Comment by Reinhard2019** [comment] 2019-04-18 02:50
Hi, I have the same problem. I use karma.

When I modified the karma.conf.js, I replaced the browser from PhantomJS to chrome, the bug is disappeared.

```
// browsers: ['PhantomJS'],
browsers: ['ChromeHeadless'],
```

I still didn't know why, but hope it can help you.

**Comment by eddyerburgh** [comment] 2019-04-27 10:26
I'm going to close this issue since there isn't a reproduction.

@codebryo It's possible that different Vue or vue-template-compiler versions cause an issue with vue-test-utils, but we run compat tests on different versions to catch any discrepancies. 

@GreggOD Can you create a separate issue to improve the docs for the`find` fail case?

@Reinhard2019 I can't help without a reproduction. But since Phantom is deprecated it might remain unfixed.

**Closed as completed by eddyerburgh** 2019-04-27 10:26 UTC

**Comment by GreggOD** [comment] 2019-04-28 14:36
Thanks Eddy.

I think for now im giving up on testing. Seems to be too many catch cases and work arounds. Im sure in the future it will be more stable. Also the way my company runs projects is unstable and constant changes resulting in too many test updates and rewrites. Consuming too much of my time.

**Comment by DesiredName** [comment] 2019-09-19 07:31
Hi! I just came across the same issue.
Here is a link to a test project: [repo](https://github.com/DesiredName/test-utils).
When run test, wrapper contains correct html, but calling *wrapper.find* always returns an empty object
