### ISSUE TITLE
Triggering a "click" on a button with type="submit" doesn't fire the "submit" event on the containing form

### ISSUE THREAD

**Issue by thejcannon** [vuejs/vue-test-utils#1278] opened 2019-07-19 17:12 UTC
### Version
1.0.0-beta.29

### Reproduction link
[https://codesandbox.io/s/vue-template-2txst](https://codesandbox.io/s/vue-template-2txst)

### Steps to reproduce
(I can't seem to get the tests to not fail with "Cannot read property 'Ctor' of undefined")

Once the tests work though, simply running them should outline the bug.

### What is expected?
When I click the "submit" button, the form "submit" listener to be called.

### What is actually happening?
It isn't being called.

**Comment by aholzner** [comment] 2019-08-19 09:55
You can trigger submit instead of click.

`submitButton.trigger('submit');` or `wrapper.find('form').trigger('submit')`

**Comment by thejcannon** [comment] 2019-08-24 14:40
Well sure, but I'd my test to not make assumptions about the code. For instance, perhaps the submit code happens on a click listener on the button _or_ it happens on the form submission. Either way clicking the button would do the right thing in the production environment, so I want to write my tests in a way that doesn't assume the _how_, just the _what_.

**Comment by aholzner** [comment] 2019-08-24 15:11
@thejcannon Well, based on your code, your are listening to, "submit," event.
```
<form @submit.prevent="submit">
    <button type="submit">Submit me</button>
    <p>{{ submittedCalled }}</p>
  </form>
```
So, I would say finding the button and triggering a submit, would reflect your code. Or you can listen to "click," event if that's what you want. Oh, one thing, If I'm not mistaken, you are not, "clicking" on a button in your tests, you are triggering an event.

**Comment by vvanpo** [comment] 2019-11-29 19:09
@thejcannon this is a problem with `jsdom` version 12, which is fixed in https://github.com/jsdom/jsdom/releases/tag/13.1.0

The problem is that `@vue/test-utils` constrains `jsdom` to `^12`, so the fix is to upgrade to 13.1.

**Edit:** I was wrong, `@vue/test-utils` doesn't actually depend on `jsdom`, only the root (private) package does for running its own tests. So this sounds like a different problem.

**Edit 2:** It's jest's fault:
  * In the 24.8.0 version you are using: https://github.com/facebook/jest/blob/v24.8.0/packages/jest-environment-jsdom/package.json#L18
  * https://github.com/facebook/jest/issues/9172

**Comment by vvanpo** [comment] 2019-11-29 19:54
So I think we can close this, @thejcannon , since it is unrelated to `@vue/test-utils` and will be fixed in Jest 25: https://github.com/facebook/jest/pull/8862

**Comment by lmiller1990** [comment] 2020-04-06 23:34
Yep, I had this problem recently. It's jsdom! Bugs are few and far in jssom, which is a remarkable - implementing a whatwg dom is an extremely complex endeavor. 

Anyway, I just use `trigger('submit')` on the form. I believe this is what a browser does anyway; clicking a button in a form triggers the form's submit event.

If someone can reproduce this with jest 25 (you need to install https://www.npmjs.com/package/jest-environment-jsdom-sixteen) please comment and we will reopen this.

**Closed as completed by lmiller1990** 2020-04-06 23:34 UTC
