### ISSUE TITLE
Cannot trigger method updated Vue lifecycle

### ISSUE THREAD

**Issue by ghost** [vuejs/vue-test-utils#455] opened 2018-03-06 04:02 UTC
### Version
1.0.0-beta.11

### Reproduction link
[https://github.com/dungla4/vue-test-utils-vuex-router](https://github.com/dungla4/vue-test-utils-vuex-router)

### Steps to reproduce
- Clone repo then run: `npm install` or `yarn install`
- Run command: `npm test` or `yarn test`

### What is expected?
Should call `updated` Vue lifecycle method and print in log

### What is actually happening?
Not trigger `updated` method, just trigger `mounted` method

---
Normally, `updated` is triggered when template is changed. I tried to change data by `wrapper.setData`, or set data directly via `wrapper.vm.msg = ..` but no luck. This function works well if you run project by command `yarn start` and click some link at the bottom of page

**Comment by 38elements** [comment] 2018-05-18 10:20
@eddyerburgh 
In real Vue, When `vm._watcher.sync` is `true`, `updated` hook is not called.
Do you think when `vm._watcher.sync` is `true`, `updated` hook should be called in Vue Test Utils?

**Comment by eddyerburgh** [comment] 2018-05-18 12:10
No, I think the solution is to either make a change to Vue core, or reimplement `update`. Changing the render watcher to sync has caused bugs that can't be fixed without changes to Vue core, or hacky code.

**Comment by 38elements** [comment] 2018-05-18 13:44
Thank you for reply.
I think in order to solve this problem which `updated` hook is not executed when `sync` mounting option is `true`,
 it is necessary to let Vue instance to do different behavior from the real Vue instance.

If you are not resolving this issue currently,
I think I try to resolve this issue.

**Comment by 38elements** [comment] 2018-05-18 15:00
Even if the behavior is different,
I think it is better to call `updated` hook synchronously when `vm._watcher.sync` is `true`.

**Comment by eddyerburgh** [comment] 2018-05-18 15:19
Ok, that would be great if you could investigate. I'd be interested to see a solution. I'm going to investigate changing Vue core to add a sync option this weekend so we can compare solutions 👍

**Comment by 38elements** [comment] 2018-05-18 15:43
I am sorry.
Since I have work to do on this Saturday and Sunday,
I may not be able to make deliverable.
I will make deliverable within 8 days.

**Comment by eddyerburgh** [comment] 2018-05-18 17:54
That's fine, this issue might take a while to solve. 

Another bug caused by setting the watcher to sync is that a listeners warning is thrown. I described the problem [here](https://github.com/vuejs/vue-test-utils/issues/532/#issuecomment-386798651), and I'm not sure there's a fix apart from setting Vue to silent while the render watcher runs, which would swallow errors.

**Comment by 38elements** [comment] 2018-06-02 00:34
This issue was resolved at #675.

**Closed as completed** 2018-07-29 04:52 UTC
Labels: bug, sync
