### ISSUE TITLE
find(Component).exists() always returns true

### ISSUE THREAD

**Issue by BeniRupp** [vuejs/vue-test-utils#810] opened 2018-07-06 10:06 UTC
### Version
1.0.0-beta.20

### Reproduction link
[https://github.com/BeniRupp/vue-test-utils-getting-started](https://github.com/BeniRupp/vue-test-utils-getting-started)

### Steps to reproduce
Run the tests using `npm test`.

### What is expected?
The `hello` component is not be rendered because of `v-if="false"`, therefore the `wrapper.find(Hello).exists()` should return `false`. Furthermore `wrapper.findAll(Hello).length` should be `0`.

### What is actually happening?
`wrapper.find(Hello).exists()` returns `true` and `wrapper.findAll(Hello).length` returns `2`. Furthermore the HTML of the `Hello` component is the same as the HTML of the wrapper. Whereas `wrapper !== wrapper.find(Hello)`.

When using `wrapper.find('.hello-message')` the `expect` method returns `false` and `findAll()` did not find any `Hello` component as expected.

---
For me it seems to be a bug of the `find(Component)` method when using `mount()`. If I use `shallowMount()` the `find` method will work as expected.

The issue can also be reproduced using vue-test-utils `1.0.0-beta.13`.

**Comment by eddyerburgh** [comment] 2018-07-06 10:35
Thanks for the bug report.

This is a duplicate of https://github.com/vuejs/vue-test-utils/issues/744, and will be fixed in the next release

**Closed as completed by eddyerburgh** 2018-07-06 10:35 UTC
Labels: bug
