### ISSUE TITLE
https://github.com/rudolfbyker/reproduce-vue-test-utils-emitted

### ISSUE THREAD

**Issue by rudolfbyker** [vuejs/vue-test-utils#1510] opened 2020-04-22 07:37 UTC
### Version
1.0.0-beta.33

### Reproduction link
[https://github.com/rudolfbyker/reproduce-vue-test-utils-emitted](https://github.com/rudolfbyker/reproduce-vue-test-utils-emitted)

### Steps to reproduce
Look at these lines `src/components/__tests__/testOuterComponent.test.js` in the reproduction repo:

```javascript
    // With this method, the test fails.
    // const inner = outer.find(".test-inner-component");

    // With this method, the test passes.
    const inner = outer.find(TestInnerComponent);
```

Run the test using `yarn test:unit`. It passes. Now switch to the other find method and run the test again. It will fail.

Moreover, if you uncomment the watcher in the TestOuterComponent, the text "Something else!" appears in `outer.emitted()` when the inner component was found via the class, but it is overwritten by "AAAAAAARGH" when the inner component was found via CSS selector.

### What is expected?
Emitted should contain the same data, regardless of how the component was found. `outer.emitted()` should not contain anything, if it never emits anything. If it does emit "Something else!",  then `outer.emitted()` should contain that string.

### What is actually happening?
When finding the inner component using a CSS selector, the outer component's `emitted()` contains the data that was emitted by the inner component. When the outer component also emitted something, that is overwritten by what the inner component emitted. This only happens when finding the inner component via CSS selector.

---
I know that some people regard finding components by class as the "correct way", but the docs say that both should work, and I really need to find it using CSS selectors, since some Vuetify components are hard to find via class name. If you import them in tests, jest doesn't always know how to transpile them properly.

**Comment by lmiller1990** [comment] 2020-04-24 09:56
Any reason you are using `vm.$emit`? Why not `find('button').trigger('click')`?

This is intended behavior - DOM elements to not emit events, components do, that is a Vue component API.

**Comment by rudolfbyker** [comment] 2020-04-24 10:43
> Any reason you are using `vm.$emit`? Why not `find('button').trigger('click')`?

Because I want to test what happens when the child component emits something. In my real world case, the emitted value is not just dependant on the click (or in some cases, cannot be caused by user interaction like clicks or keypresses). But this is irrelevant. The reproduction is obviously just contrived to demonstrate the bug.

> This is intended behavior - DOM elements to not emit events, components do, that is a Vue component API.

It's not a DOM element. According to the docs, you should be able to vind Vue components and use the Vue API even when you find the component using CSS selectors.

I just ran it through the debugger again: Even when you use CSS selectors, you get a VueWrapper object back, not a DOM element.

**Comment by lmiller1990** [comment] 2020-04-24 12:04
Hm, interesting. I pulled the code and tried it out. `console.log` reveals they are both VueWrapper, but not the same thing:

```
console.log src/components/__tests__/testOuterComponent.test.js:22
    VueWrapper {
      isFunctionalComponent: undefined,
      _emitted: [Object: null prototype] {},
      _emittedByOrder: [],
      selector: {
        name: 'TestInnerComponent',
        props: { value: [Object] },
        render: [Function: render],
        staticRenderFns: [],
        _Ctor: { '2': [Function] }
      }
    }

  console.log src/components/__tests__/testOuterComponent.test.js:23
    VueWrapper {
      isFunctionalComponent: undefined,
      _emitted: [Object: null prototype] {},
      _emittedByOrder: [],
      selector: '.test-inner-component'
    }
```

I guess this makes sense. In the above, the first is the component selector. Second is CSS selector. When you search with a CSS selector, you are not getting the Vue component, but the root VNode.

The event is just propagating - this is intended, right? If any event is emitted in a child, the parent will catch it. `emitted` is just capturing all those events. Correct me if I am wrong but you are expecting that once the event is captured by `emitted`, it should stop propagating and not be captured by the higher up `emitted?

I think this is working exactly how it should - the parent (`OuterComponent`) is just capturing an event it "hears". 

I am not super clear on how this blocks you testing Vuetify - happy to provide some guidance if you have a specific case you are having trouble with. I have had best success using `mount` and interacting with the DOM elements via `trigger` for Vuetify.

Re: the docs comment - yep, you can find components and use the Vue API with CSS selectors if you are finding a node with a vm (like you are here) - I misunderstood the reproduction case at first look. Sorry about that.

**Comment by rudolfbyker** [comment] 2020-04-24 12:15
> When you search with a CSS selector, you are not getting the Vue component, but the root VNode.

This is a VERY important and non-obvious piece of info that should be made very clear in the docs.

> Correct me if I am wrong but you are expecting that once the event is captured by emitted, it should stop propagating and not be captured by the higher up `emitted?

As stated originally, I am merely expecting it to work the same, regardless of how you use "find". If there is a way to get from the "root VNode" to the "Vue component" after using find with a CSS selector, then that would also solve my problem. But once again, it needs to be documented.

**Comment by lmiller1990** [comment] 2020-04-24 13:28
Sure, we can update the docs. The docs for this library are definitely not great, along with what is a pretty complex library that delves into Vue's internals quite a bit.

What do you think we should include to make this more clear? You can make a PR, or suggest something and I can add it.

PS: we are looking to make the docs a lot more concise and simple for VTU next (for Vue 3). If this is something that interests you, those are found [here](https://github.com/vuejs/vue-test-utils-next-docs/) and there is lots of opportunity to contribute - pick an issue and tag me and we can get rolling. 

Eventually I would like to clean these docs up a lot as well, as you said they can be confusing.

**Comment by lmiller1990** [comment] 2020-04-27 10:00
Closing this one for now, but happy to accept a PR to improve docs.

**Closed as completed** 2020-04-27 09:59 UTC
