### ISSUE TITLE
test utils coverage report broken for Vue2 projects

### ISSUE THREAD

**Issue by MikeOverbeck** [vuejs/vue-test-utils#1977] opened 2022-05-28 21:05 UTC
### Version
1.3.0

### Reproduction link
[github.com](https://github.com/MikeOverbeck/vue2testingbug)

### Steps to reproduce
create a vue2 app with Jest unit testing with vue create
add `collectCoverage: true` in jest.config.js
write a method in the HelloWorld.vue component. Do not write a unit test for it.
`yarn test:unit`
jest will falsely report 100% code coverage in its reporting.

### What is expected?
coverage report under 100% for untested code.

### What is actually happening?
While test are running and pass/failing appropriately, none of the code within the `export default{}` block of components is being counted in the code coverage report, always resulting in a 100% coverage report.

---

**Comment by MikeOverbeck** [comment] 2022-05-28 21:56
Upgraded @vue/test-utils to 1.3.0 in repo to confirm bug persists with latest version

**Comment by lmiller1990** [comment] 2022-06-14 00:36
I think this bug needs to be fixed in Vue Jest, since that's what instruments the code coverage for Jest.

Projects definitely have code coverage working for Vue with Jest, though. I wonder if it's a config issue.

**Comment by 1amardeep** [comment] 2022-06-27 04:05
Same issue is reported on stackoverflow. 
https://stackoverflow.com/questions/72674342/vue-2-coverage-issue-getting-different-behaviour-for-vue-2-and-vue-3

**Comment by cpontvieux-systra** [comment] 2022-12-09 15:27
https://github.com/vuejs/vue-jest/issues/480

**Comment by ebisbe** [comment] 2023-01-20 14:57
> [vuejs/vue-jest#480](https://github.com/vuejs/vue-jest/issues/480)

Reading the comments seems the issue is not here. Closing for now.

**Closed as completed by ebisbe** 2023-01-20 14:57 UTC
