### ISSUE TITLE
ReferenceError: requestAnimationFrame is not defined

### ISSUE THREAD

**Issue by xinde** [vuejs/vue-test-utils#974] opened 2018-09-19 10:23 UTC
### Version
1.0.0-beta.20

### Reproduction link
[https://jsfiddle.net/50wL7mdz/734408/](https://jsfiddle.net/50wL7mdz/734408/)

### Steps to reproduce
mocha/chai test a .vue file that contains requestAnimationFrame
default eslint config
--------------------
ReferenceError: requestAnimationFrame is not defined

### What is expected?
no this warning

### What is actually happening?
ReferenceError: requestAnimationFrame is not defined

### eslint config
```
{
  "name": "xxx",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "test:unit": "vue-cli-service test:unit",
    "test:e2e": "vue-cli-service test:e2e"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.4",
    "@fortawesome/free-solid-svg-icons": "^5.3.1",
    "@fortawesome/vue-fontawesome": "^0.1.1",
    "@tweenjs/tween.js": "^17.2.0",
    "axios": "^0.18.0",
    "echarts": "^4.2.0-rc.1",
    "element-ui": "^2.4.7",
    "normalize.css": "^8.0.0",
    "vue": "^2.5.17",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.3",
    "@vue/cli-plugin-e2e-cypress": "^3.0.3",
    "@vue/cli-plugin-eslint": "^3.0.3",
    "@vue/cli-plugin-unit-mocha": "^3.0.3",
    "@vue/cli-service": "^3.0.3",
    "@vue/eslint-config-standard": "^3.0.3",
    "@vue/test-utils": "^1.0.0-beta.20",
    "chai": "^4.1.2",
    "node-sass": "^4.9.0",
    "sass-loader": "^7.0.1",
    "vue-template-compiler": "^2.5.17"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "@vue/standard"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}

```

**Comment by bugsduggan** [comment] 2018-09-20 13:48
I have recently been experiencing a similar issue - I even got as far as creating a repro repo [here](https://github.com/bugsduggan/vue-test-utils-bug) but you beat me to the bug report.

In my case, I'm using typescript with mocha+chai in addition to vuetify (repo created with @vue/cli v3).

My instinct tells me that we're just missing a polyfill or a shim somewhere but despite my best efforts, I've not been able to reliably find a fix for this myself.

**Comment by xinde** [comment] 2018-09-21 01:58
@bugsduggan I still don't know how to fix it.A lot of information has been searched, but no solution has been found :(

**Comment by eddyerburgh** [comment] 2018-09-22 06:38
The issue is that jsdom-global doesn't add `requestAnimationFrame` to the `global` object.

The immediate fix is to add `requestAnimationFrame` to the `global` object before your tests run:

```
global.requestAnimationFrame = cb => cb()
```

To include `requestAnimation` with jsdom, you must pass in the `pretendToBeVisible` option.

```js
const window = (new JSDOM(``, { pretendToBeVisual: true })).window;
```

I created a PR in vue-cli to get this added to the mocha unit plugin—https://github.com/vuejs/vue-cli/pull/2573

**Closed as completed by eddyerburgh** 2018-09-22 06:38 UTC

**Comment by JamesMcMahon** [comment] 2019-08-02 20:41
@eddyerburgh I still see this issue and I am making an assumption that the merge PR you linked to is now released. 

Is there anything I need to do specifically to use the functionality you added in the PR? Anything I need to set in my configuration?

Quite possible I am seeing an issue with the same symptom but different cause, but wanted to double check.

I can confirm in my tests that adding

```
// at top
declare const global: any

// before test
global.requestAnimationFrame = (cb: any) => cb();
```

Fixes the issue.

**Comment by eddyerburgh** [comment] 2019-09-08 06:23
Hi @JamesMcMahon, sorry that you're experiencing this issue.

Can you open an issue in the [vue-cli](https://github.com/vuejs/vue-cli) repo. That's the repo where the fix was made to

**Comment by nargeszmn** [comment] 2019-11-06 14:54
Hi @eddyerburgh . I still see this issue when trying to run my tests. 
I am using 

- **mocha/chai**, "

- @vue/cli-plugin-unit-mocha": "^**4.0.5**, 

- @vue/cli-service": "^**4.0.5** and 

- @vue/test-utils": "**1.0.0-beta.29**. 

I still don't know how to fix this issue. Can you help me to figure out the source of the problem, and a way to be able to fix it?

**Comment by zzhenryquezz** [comment] 2020-02-20 03:15
Just a note this could happen in ts projects too, and to resolve this problem you have to define the global function in runtime.

**tests/setup.ts:**
``` ts
const requestAnimationFrame = (fn: Function) => fn();
globalThis.requestAnimationFrame = requestAnimationFrame;
```
And make sure that the setup.ts file is require before run the tests in npm script

**package.json:**
```
"test": "vue-cli-service test:unit --include ./tests/setup.ts --recursive ./__tests__/",
```

**Comment by klyntonhjr** [comment] 2020-03-11 18:03
I'm using Mocha+Chai for my testing, and Vuetify for my component library.

To fix this issue I just added the following to the top of my component.spec.js file
`global.requestAnimationFrame = function () {}` 

I was having this issue when I added a Vuetify [**v-text-field** component ](https://vuetifyjs.com/en/components/text-fields/)in the template of my Vue file

I'm using versions (not sure all packages that are relevant),
```
"devDependencies": {
    ...
    "@vue/cli-plugin-unit-mocha": "~4.2.0",
    "@vue/cli-service": "~4.2.0",
    "@vue/test-utils": "1.0.0-beta.31",
    "chai": "^4.1.2",
    "vue-cli-plugin-vuetify": "~2.0.5",
    "vue-template-compiler": "^2.6.11",
    "vuetify-loader": "^1.3.0"
    ...
}
```

**Comment by campbellgoe** [comment] 2022-09-17 10:19
the loop is event based, based on a particular wavelength or something, I think it's related to electricity pulses. otherwise you could have user input with a mouse which has x and y as input and when it moves it executes the code, but if you were to make a loop without input such as raf, it would have to go into stable diffusion. Actually the argument passed to raf is a delta (change/difference in time).
