### ISSUE TITLE
How to unit test vue-mapbox

### ISSUE THREAD

**Issue by stivenramireza** [vuejs/vue-test-utils#1696] opened 2020-09-24 18:27 UTC
Recently I have problems with my unit tests when I need to test an own component which uses a Vue MapBox component like **MglMarker**.

That's the component I trying test:

```javascript
<template>
  <div>
    <div v-if="experimentName === 'price-marker'">
      <div v-if="variant === 'icon'">
        <MglMarker
          v-for="(item, index) of properties"
          :key="index"
          :coordinates="[item.property.longitude, item.property.latitude]"
        >
          <img
            v-if="propertyHover === index"
            slot="marker"
            class="icon-marker-selected"
            src="@/assets/img/markers/selected.png"
            @click="selectMarker(item)"
            @mouseleave="setPropertyHover(-1)"
          />
          <img
            v-if="propertyHover !== index"
            slot="marker"
            class="icon-marker"
            src="@/assets/img/markers/no-selected.png"
            @click="selectMarker(item)"
            @mouseenter="setPropertyHover(index)"
          />
        </MglMarker>
      </div>
      <div v-if="variant === 'price'">
        <MglMarker
          v-for="(item, index) of properties"
          :key="index"
          :coordinates="[item.property.longitude, item.property.latitude]"
        >
          <div
            v-if="propertyHover === index"
            slot="marker"
            class="price-marker-selected"
            @click="selectMarker(item)"
            @mouseleave="setPropertyHover(-1)"
          >
            <h5 class="price-text">{{ item.sellValue | toPesos }}</h5>
          </div>
          <div
            v-if="propertyHover !== index"
            slot="marker"
            class="price-marker"
            @click="selectMarker(item)"
            @mouseenter="setPropertyHover(index)"
          >
            <h5 class="price-text">{{ item.sellValue | toPesos }}</h5>
          </div>
        </MglMarker>
      </div>
    </div>
  </div>
</template>

<script>
import { MglMarker } from 'vue-mapbox'
import { mapMutations, mapState } from 'vuex'
export default {
  filters: {
    toPesos: value => {
      return value !== 'Precio'
        ? `$${('' + value).replace(/\B(?=(\d{3})+(?!\d))/g, ',')}`
        : value
    }
  },
  components: {
    MglMarker
  },
  props: {
    properties: {
      type: Array,
      default: () => {
        return []
      }
    },
    generateDetailUrl: {
      type: Function,
      default: () => {
        return ''
      }
    }
  },
  data() {
    return {
      experimentName: this.$exp.name,
      variant: this.$exp.$activeVariants[0]
    }
  },
  computed: {
    ...mapState({
      propertyHover: state => state.search.propertyHover
    })
  },
  methods: {
    ...mapMutations({
      setPropertyHover: 'search/setPropertyHover'
    }),
    selectMarker(item) {
      this.$router.push(this.generateDetailUrl(item))
    }
  }
}
</script>
```

That's the failed test:

```javascript
import Vuex from 'vuex'
import { shallowMount, createLocalVue } from '@vue/test-utils'
import MapMarker from '@/components/map/MapMarker.vue'
import MglMarker from 'vue-mapbox'

const localVue = createLocalVue()
localVue.use(Vuex)
localVue.use(MglMarker)

describe('MapMarker.vue', () => {
    let state
    let store

    const $exp = {
        name: 'price-marker',
        $activeVariants: ['icon']
    }

    const mapMarkerProps = {
        properties: [
            {
                id: 1,
                rentValue: 1800000,
                status: 'PROMOTION',
                type: 'APARTMENT'
            },
            {
                id: 2,
                rentValue: 420000,
                status: 'PROMOTION',
                type: 'APARTMENT'
            }
        ],
        generateDetailUrl: () => {
            return '/apartment-to-rent/neighborhood-city/10000'
        }
    }

    const mapMarkerData = {
        experimentName: 'price-marker',
        variant: 'icon'
    }

    beforeEach(() => {
        state = {
            propertyHover: -1
        }

        store = new Vuex.Store({
            modules: {
              search: {
                state
              }
            }
        })
    })

    it('render correct MglMarker component', () => {
        const wrapper = shallowMount(MapMarker, {
            localVue,
            store,
            mocks: {
                $exp
            }
        })
        wrapper.setProps(mapMarkerProps)
        wrapper.setData(mapMarkerData)
        expect(wrapper.findComponent(MglMarker).exists()).toBe(true)
    })

})
```
How can I fix it?

Thanks in advance!

**Comment by lmiller1990** [comment] 2020-09-25 00:07
This is not really intended as a Q&A board. What is does `MglMarker` look like? Basically impossible to help without a reproduction or at least the relevant component you are testing.

**Comment by stivenramireza** [comment] 2020-09-25 00:13
> This is not really intended as a Q&A board. What is does `MglMarker` look like? Basically impossible to help without a reproduction or at least the relevant component you are testing.

Excuse me @lmiller1990 , I'll add right now.

**Comment by stivenramireza** [comment] 2020-09-25 00:34
@lmiller1990 I've already edited my question and excuse me again.

**Comment by vinayakkulkarni** [comment] 2020-09-29 10:02
@stivenramireza : I'm planning on adding more test in the forked version of `vue-mapbox` (sadly the owner is afk since last year) - [`v-mapbox`](https://github.com/geospoc/v-mapbox)

**Comment by lmiller1990** [comment] 2020-10-01 07:44
You could try using the mounting options:

```
const wrapper = mount(MapMarker, {
  propsData: {
    // ...
  },
  data() {
    return {
      // ...
    }
  }
})
```

Does this work? The next thing to do would be `console.log` until you figure out what's missing - it's not immediately clear to me looking at this.

I am going to close this for now since I don't see any issue with VTU - you can keep posting here and we can work through this if you want, though. If you cannot find `MglMarker`, `variant` must not be set.

Another alternative would to try `mount` and see if you get any more useful info.

**Closed as completed by lmiller1990** 2020-10-01 07:44 UTC
