### ISSUE TITLE
Object.assign and Promise polyfills for PhantomJS should be in the lib

### ISSUE THREAD

**Issue by pushrbx** [vuejs/vue-test-utils#222] opened 2017-12-01 00:04 UTC
I had an issue few days ago where I had the following error with PhantomJS:
```
TypeError: undefined is not a constructor (evaluating 'Object.assign({}, getCoreProperties(originalComponent),
        {render: function () {}})') in C:/Users/pushrbx/AppData/Local/Temp/62c1b89f497f48b7f174ed60740afe2c.browserify (line 8651)
    createBlankStub@c:/Users/pushrbx/AppData/Local/Temp/node_modules/vue-test-utils/dist/vue-test-utils.js:86:0 <- C:/Users/pushrbx/AppData/Local/Temp/62c1b89f497f48b7f174ed60740afe2c.browserify:8651:23
    c:/Users/pushrbx/AppData/Local/Temp/node_modules/vue-test-utils/dist/vue-test-utils.js:104:0 <- C:/Users/pushrbx/AppData/Local/Temp/62c1b89f497f48b7f174ed60740afe2c.browserify:8669:51
    forEach@[native code]
```
And I only could solve it by adding the following npm package: https://www.npmjs.com/package/phantomjs-polyfill-object-assign
Of course a babel-polyfills package would solve it as well.
I would suggest that the pollyfills (Object.assign, Promises) for PhantomJS should be included in vue-test-utils.
@eddyerburgh I tag you here, because you told me on discord to create this issue. :)

**Comment by LinusBorg** [comment] 2017-12-01 13:33
I would not see this as a prop. Polyfilling the environment should not be considered a primary feature of this lib (but a nice-to-have).

The lib itself should be agnostic to the environment it is used in and the browser features available.

Don'T get me wrong, we an add this - but it's not a bug in my eyes.

**Comment by pushrbx** [comment] 2017-12-01 13:41
I agree with you, so let me modify my above statement:
It would be nice if the lib would put a warning in the console log saying that these objects require polyfills. But even this solution sounds a bit like out of the scope of the lib.

**Comment by eddyerburgh** [comment] 2017-12-03 20:10
I added an object.assign polyfill. It will be in the next release

**Closed by eddyerburgh** 2017-12-03 20:10 UTC
Labels: intend to implement
