### ISSUE TITLE
Prop declared in mixin is not recognized when using shallowMount

### ISSUE THREAD

**Issue by lusarz** [vuejs/vue-test-utils#1096] opened 2019-01-14 13:20 UTC
### Version
1.0.0-beta.28

### Reproduction link
[https://github.com/lusarz/vue-test-utils-examples/commit/1ab138962e9530d24381bad22f411abd9a488093](https://github.com/lusarz/vue-test-utils-examples/commit/1ab138962e9530d24381bad22f411abd9a488093)

### Steps to reproduce
- create [child component](https://github.com/lusarz/vue-test-utils-examples/blob/1ab138962e9530d24381bad22f411abd9a488093/src/components/Child.vue) that use [mixin](https://github.com/lusarz/vue-test-utils-examples/blob/1ab138962e9530d24381bad22f411abd9a488093/src/mixins/simple-mixin.js) with prop declared [inside it](https://github.com/lusarz/vue-test-utils-examples/blob/1ab138962e9530d24381bad22f411abd9a488093/src/mixins/simple-mixin.js#L3)
- use child component in parent component
- [create test](https://github.com/lusarz/vue-test-utils-examples/blob/1ab138962e9530d24381bad22f411abd9a488093/test/unit/specs/Parent.spec.js#L8) which checks if child has appropriate props passed, using shallowMount

### What is expected?
Prop has appropriate value

### What is actually happening?
Prop is `undefined`

---
When I either use `mount` or declare props directly in child component everything works

**Comment by eddyerburgh** [comment] 2019-01-15 21:40
Thanks for the bug report. This is a duplicate of #1094 so I'm closing this in favor of #1094

**Closed as completed** 2019-01-16 20:30 UTC
Labels: bug
