### ISSUE TITLE
find throws error when using refs

### ISSUE THREAD

**Issue by unclejustin** [vuejs/vue-test-utils#1477] opened 2020-03-19 05:00 UTC
### Version
1.0.0-beta.30

### Reproduction link
[https://gitlab.com/unclejustin/test-utils-but](https://gitlab.com/unclejustin/test-utils-but)

### Steps to reproduce
In a test reference an element by ref. Then try to find anything in that element using anything other than a dom selector:

const button = wrapper.find({ ref: "testButton" });
expect(button.find(Icon).exists()).toBe(true);

This will throw the errror "[vue-test-utils]: cannot find a Vue instance on a DOM node. The node you are calling find on does not exist in the VDom. Are you adding the node as innerHTML?"

### What is expected?
That found elements have the same functionality as root wrappers.

### What is actually happening?
Throwing an error.

---
I think this should work as described, but if I am wrong then maybe the docs just need to be updated to reflect the actual functionality?

**Comment by lmiller1990** [comment] 2020-03-20 06:54
Without digging my guess is since you are using `shallowMount`, a stub is rendered instead of the actual component, which does not have the ref (maybe). My understanding is a `ref` is a static reference to a DOM element, and since the stub is a different component to the actual one with the ref, it isn't finding it.

What happens if you use `mount`?

**Comment by unclejustin** [comment] 2020-03-20 20:45
Same issue. Sorry, I should have mentioned that I tried that already as well.

**Comment by unclejustin** [comment] 2020-03-20 20:47
If it helps, here is where it is failing: https://github.com/vuejs/vue-test-utils/blob/be4033e2e22440255441a9ab9e1fe717a2c456a0/packages/test-utils/src/find.js#L58

**Comment by dobromir-hristov** [comment] 2020-03-21 15:11
Hey I think this is just a limitation of how you are chaining off `find` to a normal html component. We are kind of limited on how we can use `find` to search for components.
If you use a DOM selector instead of a Vue component, it should work.

The problem is, we cant find a Vue component by it's dom node, as that node could have a few components. And we cant search by Vue components, when we go down to DOM level :/

**Comment by unclejustin** [comment] 2020-03-21 16:24
That's what I was seeing as well stepping through the code. It's cool, I'm going to try and work up a PR to make the docs more clear that this is a limitation.

**Comment by unclejustin** [comment] 2020-03-22 01:40
PR here: https://github.com/vuejs/vue-test-utils/pull/1481

**Comment by Stoom** [comment] 2020-04-07 00:18
Can this be closed in lue of #1498 ?

**Closed as completed** 2020-04-07 01:13 UTC
