### ISSUE TITLE
@toast-ui/vue-editor TypeError only while testing

### ISSUE THREAD

**Issue by dsvanidze** [vuejs/vue-test-utils#1488] opened 2020-03-24 19:14 UTC
### Version
1.0.0-beta.32

### Reproduction link
[http://nourl.no](http://nourl.no)

### Steps to reproduce
import Vue from "vue";
import { mount } from "@vue/test-utils";
import { Editor } from "@toast-ui/vue-editor";

describe("MarkdownEditor.vue", () => {
  it("should render markdown editor element", () => {
    const wrapper = mount(Editor);
  });
});

### What is expected?
To render toast-ui editor for markdowns without errors.

### What is actually happening?
```
[Vue warn]: Error in mounted hook: "TypeError: Right-hand side of 'instanceof' is not an object"
    
    found in
    
    ---> <ToastuiEditor> at src/Editor.vue
           <Root>


console.error node_modules/vue/dist/vue.runtime.common.dev.js:1884
    TypeError: Right-hand side of 'instanceof' is not an object
        at SquireExt.at.createRange (/Users/All/Projects/node_modules/@toast-ui/editor/dist/toastui-editor.js:6751:29521)
        at SquireExt.at.setHTML (/Users/All/Projects/node_modules/@toast-ui/editor/dist/toastui-editor.js:6752:11473)
        at SquireExt.P (/Users/All/Projects/node_modules/@toast-ui/editor/dist/toastui-editor.js:6751:7749)
        at new SquireExt (/Users/All/Projects/node_modules/@toast-ui/editor/dist/toastui-editor.js:15890:26)
        at WysiwygEditor.init (/Users/All/Projects/node_modules/@toast-ui/editor/dist/toastui-editor.js:16762:19)
        at Function.factory (/Users/All/Projects/node_modules/@toast-ui/editor/dist/toastui-editor.js:17910:9)
        at new ToastUIEditor (/Users/All/Projects/node_modules/@toast-ui/editor/dist/toastui-editor.js:27072:35)
        at VueComponent.mounted (/Users/All/Projects/node_modules/@toast-ui/vue-editor/dist/toastui-vue-editor.js:1:3099)
        at invokeWithErrorHandling (/Users/All/Projects/node_modules/vue/dist/vue.runtime.common.dev.js:1850:57)
        at callHook (/Users/All/Projects/node_modules/vue/dist/vue.runtime.common.dev.js:4201:7)
        at Object.insert (/Users/All/Projects/node_modules/vue/dist/vue.runtime.common.dev.js:3133:7)
        at invokeInsertHook (/Users/All/Projects/node_modules/vue/dist/vue.runtime.common.dev.js:6320:28)
        at VueComponent.patch [as __patch__] (/Users/All/Projects/node_modules/vue/dist/vue.runtime.common.dev.js:6537:5)
        at VueComponent.Vue._update (/Users/All/Projects/node_modules/vue/dist/vue.runtime.common.dev.js:3927:19)
        at VueComponent.updateComponent (/Users/All/Projects/node_modules/vue/dist/vue.runtime.common.dev.js:4048:10)
        at Watcher.get (/Users/All/Projects/node_modules/vue/dist/vue.runtime.common.dev.js:4459:25)
        at new Watcher (/Users/All/Projects/node_modules/vue/dist/vue.runtime.common.dev.js:4448:12)
        at mountComponent (/Users/All/Projects/node_modules/vue/dist/vue.runtime.common.dev.js:4055:3)
        at VueComponent.Object.<anonymous>.Vue.$mount (/Users/All/Projects/node_modules/vue/dist/vue.runtime.common.dev.js:8386:10)
        at mount (/Users/All/Projects/node_modules/@vue/test-utils/dist/vue-test-utils.js:8649:21)
        at Object.it (/Users/All/Projects/tests/unit/Collection/FormElements/MarkdownEditor.spec.ts:47:21)
        at Object.asyncJestTest (/Users/All/Projects/node_modules/@vue/cli-plugin-unit-jest/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
        at resolve (/Users/All/Projects/node_modules/@vue/cli-plugin-unit-jest/node_modules/jest-jasmine2/build/queueRunner.js:43:12)
        at new Promise (<anonymous>)
        at mapper (/Users/All/Projects/node_modules/@vue/cli-plugin-unit-jest/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
        at promise.then (/Users/All/Projects/node_modules/@vue/cli-plugin-unit-jest/node_modules/jest-jasmine2/build/queueRunner.js:73:41)
        at process._tickCallback (internal/process/next_tick.js:68:7)
```

---
I cannot understand, why the error occurs only while testing. When I use the component in a browser and render it, it works great.

**Comment by dobromir-hristov** [comment] 2020-03-24 19:34
I am almost certain that errors comes from the editor relying on browser APIs. Tests render in jsdom, which is not a real browser.
In these cases I would test my own components and stub such complicated ones.

**Comment by dsvanidze** [comment] 2020-03-26 13:02
@dobromir-hristov thank you very much for your answer. Stubs are useful generally, but it does not work in my case, because I have functional components. How can I use `mocks` to mock the functionality where error occurs?

**Comment by Stoom** [comment] 2020-03-27 00:42
I guess what are you trying to test here?  Maybe there's another way to attack that test so that you can use `shallowMount` or target the component that needs to be stubbed

**Comment by lmiller1990** [comment] 2020-04-05 13:53
@dobromir-hristov was right. It's the `Range` API. The problem is within the codemirror dependency. Here is how I tracked it down. The very first line of the error dump:

```
at SquireExt.at.createRange (/Users/All/Projects/node_modules/@toast-ui/editor/dist/toastui-editor.js:6751:29521)
```

Going to that file line wasn't useful; it's over 29000 characters long. So I just unminified it, saved it over the original file in node_modules and ran the test again. I got the same error with a differnent line (since it's not longer minified). I went to the line. It looks like this:

```
if (e instanceof this._win.Range) return e.cloneRange();
```

- I looked up `Range` support in jsdom. 
- Looks like it was only just merged a few months ago: https://github.com/jsdom/jsdom/pull/2719. 
- I then did `vi node_modules/jsdom/package.json` and saw the version is 15.x.
- Checking jsdom on GH https://github.com/jsdom/jsdom/blob/master/package.json#L3 it's at v16. - You need to have v16 installed for this to work. I tried installing v16 but it still did not work.
 - That's because jest bundles their own jsdom, which is jsdom 15 by default. 
- Lucky there is `yarn add jest-environment-jsdom-sixteen` for people who want to be on bleeding edge.
-  I installed it with `yarn add jest-environment-jsdom-sixteen`. 
- I then updated `jest.config.js` to use it:

```
module.exports = {
  preset: '@vue/cli-plugin-unit-jest',
  "testEnvironment": "jest-environment-jsdom-sixteen",
}
```

Now the test passes.

I am not sure useful it is to unit test a third party dependency - you can be confident it works, they have their own test suite. Anyway, no problem with Vue Test Utils - the problem was Range is not in jsdom 15, but you can use jsdom 16 and it works. Have fun!

**Closed as completed by lmiller1990** 2020-04-05 13:53 UTC
