### ISSUE TITLE
Testing a functional component isn't the same as a regular one (propsData)

### ISSUE THREAD

**Issue by Haroenv** [vuejs/vue-test-utils#918] opened 2018-08-13 12:15 UTC
### Version
1.0.0-beta.24

### Reproduction link
[https://codesandbox.io/s/pjlwznqq1m](https://codesandbox.io/s/pjlwznqq1m)

### Steps to reproduce
- Make a functional component
- mount it with `propsData`

### What is expected?
props are passed to the component 

### What is actually happening?
no props are passed to the component

---
You can only test a functional component with `context.props`, not with `propsData` as with other components, which means that what used to be an internal implementation detail (what kind of component it is) becomes public API for the tests now and needs to be changed if that component changes of type. See what I expected to work in the first assertion, and what eventually worked in the second assertion. I didn't find anything about this in the docs.

```js
import { mount } from '@vue/test-utils';
import FunctionalComponent from './FunctionalComponent';

it("doesn't allow you to pass propsData", () => {
  // this doesn't work but I'd like it to
  const wrapper = mount(FunctionalComponent, {
    propsData: {
      someProp: 'hi there',
    },
  });

  expect(wrapper.html()).toMatchSnapshot();
});

it('only allows you to pass context', () => {
  const wrapper = mount(FunctionalComponent, {
    context: {
      props: {
        someProp: 'hi there',
      },
    },
  });

  expect(wrapper.html()).toMatchSnapshot();
});
```

**Comment by abrenneke** [comment] 2018-12-12 01:31
Could we have a `props` option which delegates to either `propsData` or `context.props` depending on what type of component is being mounted?

**Comment by lemmycaution** [comment] 2018-12-18 14:16
Hi, updating documentation can save poor little fellows time. It took me almost an hour that it's actually  an issue belongs to vue-test-utils.

**Comment by ktquez** [comment] 2019-04-18 02:34
Any solution?

**Comment by Haroenv** [comment] 2019-04-18 08:22
a functional component works like the second example test in my post

**Comment by lmiller1990** [comment] 2019-12-16 08:45
I am going to take responsibility for this. I think we should do to things

1. update docs (definitely, this is a no brainer)
2. have the same API for functional and non-functional, and a check somewhere in the codebase depending if the component is functional or not (if there is a way to know if a component is functional, not sure if there is)

If it turns out we cannot detect if a component is functional or not, I'll abandon (2) and just do (1).

**Comment by Haroenv** [comment] 2019-12-16 08:51
Thanks @lmiller1990, that sounds like a great resolution to me!

**Comment by lmiller1990** [comment] 2019-12-19 08:51
@Haroenv so it looks like this is actually fixed? Upgrading your reproduction repro to beta-30 (or beta-29, looks like beta-28 broke this) shows all green.

Going to close this one, unless I missed something. Googlers, update your version of `vue-test-utils` to the latest (if possible) or at least beta-29.

**Closed as completed by lmiller1990** 2019-12-19 08:51 UTC
Labels: feature request

**Comment by Haroenv** [comment] 2019-12-19 09:50
I wasn't aware this was fixed, this is great news @lmiller1990, thanks!
