### ISSUE TITLE
Mock $refs

### ISSUE THREAD

**Issue by charliekassel** [vuejs/vue-test-utils#271] opened 2017-12-15 18:19 UTC
It would be useful to be able to mock $refs.

Currently, as far as I understand there is no way to test a method that calls a childs methods via $refs.

```
methodToTest ( ) {
  this.a = 1
  this.$refs.childComponent.childsMethod()
}
---
undefined is not an object (evaluating 'this.$refs.childComponent.childsMethod')
```

**Comment by Austio** [comment] 2017-12-20 04:15
@charliekassel could you provide an example where you would want to use this functionality?

**Comment by charliekassel** [comment] 2017-12-20 07:36
Perhaps it's actually stubbing rather than mocking.
For the example above where we have that method to test, I guess I would want the shallow constructor to stub that child method so it's not called, preventing the test throwing an error.
I want to test the logic contained in that `methodToTest` method without the side effects of calling `$refs.childComponent.childsMethod()`

**Comment by ddykhoff** [comment] 2017-12-20 14:53
I have a component `Approvals.vue` utilizing the `vue-toast` library. I don't need to call the library methods when testing my component.

```
<template>
    <div>
        {{ someContent }}
    </div>
    <vue-toast ref='toast'></vue-toast>
</template>

<script>
import VueToast from 'vue-toast';

export default {
    props: ['someContent'],
    components: {
        'vue-toast': VueToast
    },
    methods: {
      showToast() {
          const toast = this.$refs.toast;
          toast.showToast(this.someContent);
      },
  },
    mounted () {
        this.$refs.toast.setOptions({
            maxToasts: 3,
            position: 'bottom right'
        });
    }
}
</script>
```

And my test

```
describe('Approvals page', () => {
    const wrapper = shallow(Approvals);

    it('any test', () => {
        expect(wrapper).toBeDefined();
    });
});
```

This throws the following error and fails the test:
```
TypeError: Cannot read property 'setOptions' of undefined
```

Stubbing `$refs` would allow be to test this component, as is I cannot test anything in the `Approvals` component due to this issue.

**Comment by LinusBorg** [comment] 2017-12-23 12:43
Wouldn't that be solvable by stubbing the component that's being referenced?

messing with $refs means messing with the implementation of the component under test, which is not a good idea in my opinion.

**Comment by ddykhoff** [comment] 2018-01-02 17:45
@LinusBorg `shallow` is already stubbing the referenced component so my example still stands. The issue appears to be that the `$refs` are not populated in testing like they are in production.

**Comment by eddyerburgh** [comment] 2018-01-02 18:14
@ddykhoff can you post a code example of $refs not being populated correctly in vue-test-utils?

**Comment by ddykhoff** [comment] 2018-01-02 18:28
@eddyerburgh My original comment in the issue has the example I am facing the issue with (https://github.com/vuejs/vue-test-utils/issues/271#issuecomment-353083583). Let me know if there is more info I can provide.

**Comment by ddykhoff** [comment] 2018-01-05 16:43
@eddyerburgh I was trying to create a JSFiddle to show the issue but I'm not sure its possible to transpile within JSFiddle, or at least I don't know how. Thus vue-test-utils cannot be loaded properly. 

https://jsfiddle.net/7kgkfrbu/1/

```
Uncaught ReferenceError: require is not defined
```

Should I open another issue for this? Being able to provide JSFiddles is useful for bug reproduction.

**Comment by eddyerburgh** [comment] 2018-01-05 16:58
@ddykhoff There's an iife build that runs in browsers—https://github.com/vuejs/vue-test-utils/blob/dev/dist/vue-test-utils.iife.js. Once we've released we could add it to CDNJS. At the moment, your best bet is to copy the code from the iife into JSFiddle. You also need to include vueTemplateCompiler (https://cdn.jsdelivr.net/npm/vue-template-compiler@2.5.13/browser.js).

**Comment by ddykhoff** [comment] 2018-01-05 19:25
@eddyerburgh I got it working in JSFiddle. You can use rawgit.com as a "CDN" for the iife build. Here is the bug repro you requested (child components methods not available in `$refs`).

https://jsfiddle.net/7kgkfrbu/6/

As you can see from the console output in the `mounted` callback, `$refs` is not populated.

**Comment by eddyerburgh** [comment] 2018-01-05 21:11
Hi @ddykhoff, thanks for the fiddle.

The reason you can't call the method on the ref is because shallow stubs all the child components. The $refs object is still populated, but the toast component doesn't have any methods (because it's been stubbed).

You can use `mount` instead of `shallow` if you want to interact with a child components methods. Alternatively, you could use `shallow` and pass a custom stub:

```js
const VueToastStub = {
  render: () => {},
  methods: {
  	setOptions: () => {}
  }
}

const wrapper = shallow(Approvals, {
  stubs: {
    'vue-toast': VueToastStub
  }
})
```

**Comment by LinusBorg** [comment] 2018-01-05 22:00
So if that use case isn't one after all, I posit again: we don't have to mock refs, we can stub the components. 

And we shouldn't either, because we create situations that are not possible in a real app.

**Comment by charliekassel** [comment] 2018-01-06 11:34
@eddyerburgh I can confirm that the above technique worked for me and allowed me to test the parent method without error.

**Comment by ddykhoff** [comment] 2018-01-09 21:02
@eddyerburgh Is there an issue with referencing the `$refs` in the `mounted` callback? Using your suggestion I still see the same error

https://jsfiddle.net/7kgkfrbu/7/

**Comment by eddyerburgh** [comment] 2018-01-10 18:18
@ddykhoff That is an issue with using an HTML template instead of a template property. If you refactor your example to use a `template` property, it works as expected.

vue-test-utils doesn't support HTML templates at the moment, if you'd like to see it as a feautre, please make a new feature request issue.

**Comment by eddyerburgh** [comment] 2018-01-10 18:19
I'm going to close this issue as there are solutions to mock refs by stubbing components without a method that could potentially cause bugs.

**Closed by eddyerburgh** 2018-01-10 18:19 UTC
Labels: feature request

**Comment by GarrettGeorge** [comment] 2018-11-06 21:07
How can I mock `$refs` on the component I'm testing. If I have a computed function which calculates whether or not a div is "too tall" I need to do `this.$refs.ref.clientHeight` which is not accessible when testing. 

Because of this I need a way to mock `$refs`.

**Comment by LinusBorg** [comment] 2018-11-06 21:49
Well, if `clientHeight` isn't a real thing in a unit test anyway, why bother to test it in the context of a real component instance?

If you want to test the computed property (which smells a lot like testing implementation details), just test that function on its own, providing a simple componentInstance mock with `.call(mockObject)`:
```javascript
// your computed property
function isTooTall() {
  return this.someData - this$refs.ref.clientHeight < 100
}
```
```javascript
// your test
const mock = {
  someValue: 1000,
  $refs: {
    ref: {
      clientHeight: 910
    }
  }
}
const result YourComponent.computed.isTooTall.call(mock)

expect(result).toBe(true)
```

Generally, stuff involving dimensions should probably be tested in an end-to-end test where you can verify the correctness of the resulting behaviour (breakpoints, change of dimensions etc), not a unit test that tests implementation details. That computed prop could calculate correctly and a dozen other things only appearant in a real e2e test could make the behaviour relying on this property break.

**Comment by GarrettGeorge** [comment] 2018-11-07 15:48
@LinusBorg I'm primarily trying to just get the component to complete the render cycle without throwing an error. I guess I could just check if `this.$refs` has the property `ref`.

**Comment by rehandialpad** [comment] 2018-11-20 20:39
Im also having the same issue. I need to mock the clientWidth of an element that I'm using a $ref to retrieve. My functionality involves dynamically translating an object based on the width of the container. It's unfortunate that the $ref doesn't get updated when I modify the elements in the same way the event.target gets updated https://vue-test-utils.vuejs.org/api/wrapper/#trigger-eventtype-options

**Comment by xyyVee** [comment] 2019-05-21 07:51
same question about test $refs from `element-ui` `form` component:
```
submitFilter() {
    this.$refs.filter.validate((valid) => {
        if (valid) {
              this.$emit('submitFilter', this.formData)
          }
    })
}
```
Here is my part code of test:
```
it('submit data', () => {
    const wrapper = shallowMount(OrdersFilter, {
      localVue
    })
    wrapper.vm.formData = {
      value: 'form'
    }
    wrapper.vm.submitFilter()
    console.log(wrapper.emitted())
  })
```
I want to test if `wrapper.emmitted`, but jest throw an error about 
```
this.$refs.filter.validate is not a function
```
still not familar with `vue-test-utils`, anyone can help? thanks in advance.

**Comment by krskibin** [comment] 2019-07-03 14:02
@XiaYuYing I have the same problem with element-ui, any ideas?

**Comment by syzer** [comment] 2019-07-05 11:22
@krskibin I had same problem with **element-ui**..
I encourage you to use proper framework like: 
[vuiefy](https://vuetifyjs.com/en/)

Example workarounds might be:

1. Just use e2e test with cypress, or 
2. in code of your component 
```js
if (!this.$refs.filter.validate) {
  return false
}
```
Option 2 is how bad testing practices can destroy codebase...
So I would choose Option1.

**Comment by ffxsam** [comment] 2019-07-25 00:31
Weird syntax, no? As this is creating an object, not a Vue component:

```js
const VueToastStub = {
  render: () => {},
  methods: {
  	setOptions: () => {}
  }
}

const wrapper = shallow(Approvals, {
  stubs: {
    'vue-toast': VueToastStub
  }
})
```

Might work in standard JS, but TS is very unhappy with that. I had to do this in my code:

```ts
    // @ts-ignore
    const StubbedCropper = Vue.extend({
      methods: {
        getCroppedCanvas: () => 'placeholder',
      },
      render: () => ({}),
    });
```

**Comment by Hifounder** [comment] 2020-03-04 09:44
@xyyVee You can try this
```javascript
import { shallowMount } from '@vue/test-utils';
import { Form } from 'element-ui';
import component from '.@/components/index';

describe('index.vue', () => {
    beforeEach(() => {
        wrapper = shallowMount(component, {
            stubs: {
                'el-form': Form,
            },
        });
    });
});
```

> same question about test $refs from `element-ui` `form` component:
> 
> ```
> submitFilter() {
>     this.$refs.filter.validate((valid) => {
>         if (valid) {
>               this.$emit('submitFilter', this.formData)
>           }
>     })
> }
> ```
> 
> Here is my part code of test:
> 
> ```
> it('submit data', () => {
>     const wrapper = shallowMount(OrdersFilter, {
>       localVue
>     })
>     wrapper.vm.formData = {
>       value: 'form'
>     }
>     wrapper.vm.submitFilter()
>     console.log(wrapper.emitted())
>   })
> ```
> 
> I want to test if `wrapper.emmitted`, but jest throw an error about
> 
> ```
> this.$refs.filter.validate is not a function
> ```
> 
> still not familar with `vue-test-utils`, anyone can help? thanks in advance.

**Comment by booomerang** [comment] 2020-05-26 18:51
For me helped the way of changing `shallowMount` to `mount`, and mocking the ref method like this:
```
const mockedMethod = jest.fn()
wrapper.vm.$refs.childComponent.someMethod = mockedMethod

// link where parent method calls this.$refs.childComponent.someMethod
link.trigger('click')

await flushPromises()

expect(mockedMethod).toHaveBeenCalled()
```
Hope this may be useful for someone.

**Comment by LaraLeeChina** [comment] 2020-06-18 09:32
> @xyyVee You can try this
> 
> ```js
> import { shallowMount } from '@vue/test-utils';
> import { Form } from 'element-ui';
> import component from '.@/components/index';
> 
> describe('index.vue', () => {
>     beforeEach(() => {
>         wrapper = shallowMount(component, {
>             stubs: {
>                 'el-form': Form,
>             },
>         });
>     });
> });
> ```
> 
> > same question about test $refs from `element-ui` `form` component:
> > ```
> > submitFilter() {
> >     this.$refs.filter.validate((valid) => {
> >         if (valid) {
> >               this.$emit('submitFilter', this.formData)
> >           }
> >     })
> > }
> > ```
> > 
> > 
> > Here is my part code of test:
> > ```
> > it('submit data', () => {
> >     const wrapper = shallowMount(OrdersFilter, {
> >       localVue
> >     })
> >     wrapper.vm.formData = {
> >       value: 'form'
> >     }
> >     wrapper.vm.submitFilter()
> >     console.log(wrapper.emitted())
> >   })
> > ```
> > 
> > 
> > I want to test if `wrapper.emmitted`, but jest throw an error about
> > ```
> > this.$refs.filter.validate is not a function
> > ```
> > 
> > 
> > still not familar with `vue-test-utils`, anyone can help? thanks in advance.

I have the same question about the element UI validate not a function error, do you fix this problem? waiting~~

**Comment by juniorgarcia** [comment] 2020-07-30 21:17
This is awkward. In my case, the tests pass when ran through WebStorm, but don't pass running on terminal.

Basically because something I'm doing with `$refs` which in here are just simple HTML elements, not components.  Same problem:

```
 TypeError: Cannot read property 'contains' of undefined

      217 |     },
      218 |     clickedOutsideMainMenu(e) {
    > 219 |       if (this.$refs.mainMenuOpenBtn.contains(e.target)) return
          | ^
      220 |       this.isMainMenuOpen = this.$refs.mainMenu.contains(e.target)
      221 |     },
      222 |   },
```

`this.$refs.mainMenuOpenBtn` is just a simple `<button>`.

Switching from `shallowMount` to `mount` makes no difference.

**Edit**
I think I figured out why the tests work on WebStorm. Maybe because I ran them while debugging with breakpoints. If that's the reason, this might be happening due something that is not ready yet while I run them at the terminal. Anyway, didn't solve the problem, actually it got more weird, since I'm using an `async/await` methods with `$nextTick` but it still does not work at the terminal.

**Comment by fejj182** [comment] 2020-08-25 15:08
> For me helped the way of changing `shallowMount` to `mount`, and mocking the ref method like this:
> 
> ```
> const mockedMethod = jest.fn()
> wrapper.vm.$refs.childComponent.someMethod = mockedMethod
> 
> // link where parent method calls this.$refs.childComponent.someMethod
> link.trigger('click')
> 
> await flushPromises()
> 
> expect(mockedMethod).toHaveBeenCalled()
> ```
> 
> Hope this may be useful for someone.

It was, thanks! I was trying to put the $refs object in mocks within the mount options but never thought of doing it like this :D

**Comment by fredrivett** [comment] 2020-09-07 16:01
For those simply wanting to access a child method from a mounted component (similarly to how a parent component would use `this.$refs.componentRef.childMethod()`) you can simply call `wrapper.vm.childMethod()`, assuming you set up your mount as such:

```
const wrapper = mount(YourComponent, {
   ...
};
```

**Comment by taimoorsendoso** [comment] 2021-05-11 11:28
**In ParentComponent.vue file**
```
<ChildComponentName
      ref="childReferenceName"
      :isPreviewed="isPreviewed"
    />

this.$refs.childReferenceName.childMethodName()
```
**In Jest spec file**
```
import ChildComponentName from "components/ChildComponentName";

it("test with child component method", async () => {
    let refChildComponent;
    //mount parent component instead of shallow
    wrapper = mount( ParentComponentName  );

    refChildComponent = wrapper.vm.$refs.childReferenceName = ChildComponentName;

    //use this if you want to call actual child component's method 
    refChildComponent.childMethodName = refChildComponent.methods.childMethodName;

   //But if you just want to mock response of child component's method, use this instead of above assignment
   refChildComponent.childMethod = jest.fn().mockReturnValue(false);
    
    //your code
});
```

**Comment by kiranparajuli589** [comment] 2021-06-17 08:43
> For me helped the way of changing `shallowMount` to `mount`, and mocking the ref method like this:
> 
> ```
> const mockedMethod = jest.fn()
> wrapper.vm.$refs.childComponent.someMethod = mockedMethod
> 
> // link where parent method calls this.$refs.childComponent.someMethod
> link.trigger('click')
> 
> await flushPromises()
> 
> expect(mockedMethod).toHaveBeenCalled()
> ```
> 
> Hope this may be useful for someone.

thank you! this solved my case.
we'd a method like:
```js
closeHandler(sendFocusBackToButton) {
   this.isOpen = false
   if (sendFocusBackToButton) {
      this.$refs.button.focus()
   }
},
```
in a component like: 
```vue
<div
      ref="dropdown"
      @click="closeHandler"
    />
```
test:
```js
beforeEach(async () => {
  wrapper = await mount(MyComponent, {
    data() {
      return {
        isOpen: true
      }
    },
    stubs: {
      'test-button': TestButton
    }
  })
  wrapper.vm.$refs.button.focus = jest.fn()
})
it("should close the dropdown menu", async () => {
  await wrapper.find('.menu').trigger("click")
  expect(wrapper.find(".menu").attributes('hidden')).toBe("hidden")
})
```

**Comment by TangoPJ** [comment] 2022-07-05 07:36
> For me helped the way of changing `shallowMount` to `mount`, and mocking the ref method like this:
> 
> ```
> const mockedMethod = jest.fn()
> wrapper.vm.$refs.childComponent.someMethod = mockedMethod
> 
> // link where parent method calls this.$refs.childComponent.someMethod
> link.trigger('click')
> 
> await flushPromises()
> 
> expect(mockedMethod).toHaveBeenCalled()
> ```
> 
> Hope this may be useful for someone.

Thank you buddy, you saved my time!

**Comment by lakshay2711** [comment] 2022-08-02 14:26
I am not sure about you but I got below error after doing this:

wrapper.vm.$refs.childComponent.someMethod = mockedMethod

Error:
Possible race condition: `wrapper.vm.$refs.childReferenceName` might be reassigned based on an outdated value of `wrapper.vm.$refs.childReferenceName`.

**Comment by lakshay2711** [comment] 2022-08-02 14:28
I am not sure about you but I got below error after doing this:

wrapper.vm.$refs.childComponent.someMethod = mockedMethod

Error:
Possible race condition: `wrapper.vm.$refs.childReferenceName` might be reassigned based on an outdated value of `wrapper.vm.$refs.childReferenceName`.
