### ISSUE TITLE
findAll with Vue extended component causing errors

### ISSUE THREAD

**Issue by sygrinberg** [vuejs/vue-test-utils#248] opened 2017-12-10 13:37 UTC
When I use the "findAll" function on a component that extends another component using "extends" attribute I get this error:
`undefined is not a constructor (evaluating 'Object.entries(refOptionsObject)')
isRefSelector@webpack:///node_modules/vue-test-utils/dist/vue-test-utils.js:232:0 <- index.js:751:31
getSelectorType@webpack:///node_modules/vue-test-utils/dist/vue-test-utils.js:265:0 <- index.js:784:20
getSelectorTypeOrThrow@webpack:///node_modules/vue-test-utils/dist/vue-test-utils.js:271:0 <- index.js:790:37
findAll@webpack:///node_modules/vue-test-utils/dist/vue-test-utils.js:895:0 <- index.js:1414:44`

Here is an example code of the components I am using:
file `CompA.vue`
```javascript 
<template>
 some HTML...
</template>

<script>
  export default {
     .... some JS code
  }
</script>
```

file `CompB.vue`
```javascript 
<script>
  import CompA from './CompA'
  export default {
    extends: CompA,
     .... some JS code
  }
</script>
```
After debugging what happens, I found that "findAll" on CompB doesn't refer to is as a Vue component because in the "isVueComponent" CompB doesn't have "render" method.

**Comment by wtho** [comment] 2017-12-13 10:34
I am not sure how the component should extend another component's template. The API is [not very clear](https://vuejs.org/v2/api/#extends) about this:
> Allows declaratively extending another component [...]

 The [Vue.js Extend Test](https://github.com/vuejs/vue/blob/dev/test/unit/features/options/extends.spec.js) does not test potentially inherited templates.

**Comment by 38elements** [comment] 2017-12-21 02:25
When a component is made by `extends property`, I seem that it works.
But, When a component is made by `Vue.extend()`, it does not work.

component.vue 

```vue
<template>
  <p>
    {{ foo }}
  </p>
</template>

<script>
  export default {
    name: 'component',
    data () {
      return {
        foo: 'foo',
      }
    },
    methods: {
      baz() {
        return 'baz'
      }
    }
  }
</script>
```

```js
import Vue from 'vue'
import { mount } from '~vue-test-utils'
import Component from '~resources/components/component.vue'

describe('mount', () => {
  // This case is success.
  it('extends property', () => {
    const wrapper = mount({
      extends: Component,
      template: '<div><div>{{ foo }}</div><div>{{ bar }}</div><div>{{ baz() }}</div></div>',
      data () {
        return {
          foo: 'foo',
          bar: 'bar'
        }
      }
    })
    const wrappers = wrapper.findAll('div')
    expect(wrappers.at(0).html()).to.equal('<div><div>foo</div><div>bar</div><div>baz</div></div>')
    expect(wrappers.at(1).html()).to.equal('<div>foo</div>')
    expect(wrappers.at(2).html()).to.equal('<div>bar</div>')
    expect(wrappers.at(3).html()).to.equal('<div>baz</div>')
  })

  // This case is fail.
  it('Vue.extend', () => {
    const options = {
      template: '<div><div>{{ foo }}</div><div>{{ bar }}</div><div>{{ baz() }}</div></div>',
      data () {
        return {
          foo: 'foo',
          bar: 'bar'
        }
      }
    }
    const C = Vue.extend(Component)
    const wrapper = mount(new C(options))
    const wrappers = wrapper.findAll('div')

    console.dir(wrappers) // => WrapperArray { wrappers: [], length: 0 }

    expect(wrappers.at(0).html()).to.equal('<div><div>foo</div><div>bar</div><div>baz</div></div>')
    expect(wrappers.at(1).html()).to.equal('<div>foo</div>')
    expect(wrappers.at(2).html()).to.equal('<div>bar</div>')
    expect(wrappers.at(3).html()).to.equal('<div>baz</div>')
  })
})
```

**Comment by 38elements** [comment] 2017-12-21 14:34
These test is success.

component.vue

```vue
<template>
  <p>
    {{ foo }}
  </p>
</template>

<script>
  export default {
    name: 'component',
    data () {
      return {
        foo: 'foo',
      }
    },
    methods: {
      baz() {
        return 'baz'
      }
    }
  }
</script>
```

component1.vue

```vue
<template>
  <div><div>{{ foo }}</div><div>{{ bar }}</div><div>{{ baz() }}</div></div>
</template>

<script>
  export default {
    name: 'component',
    data () {
      return {
        foo: 'foo',
        bar: 'bar'
      }
    }
  }
</script>
```

```js
import Vue from 'vue'
import { mount } from '~vue-test-utils'
import Component from '~resources/components/component.vue'
import Component1 from '~resources/components/component1.vue'


describe('mount', () => {
  // This case is success.
  it('extends property', () => {
    const wrapper = mount({
      extends: Component,
      template: '<div><div>{{ foo }}</div><div>{{ bar }}</div><div>{{ baz() }}</div></div>',
      data () {
        return {
          foo: 'foo',
          bar: 'bar'
        }
      }
    })
    const wrappers = wrapper.findAll('div')
    expect(wrappers.at(0).html()).to.equal('<div><div>foo</div><div>bar</div><div>baz</div></div>')
    expect(wrappers.at(1).html()).to.equal('<div>foo</div>')
    expect(wrappers.at(2).html()).to.equal('<div>bar</div>')
    expect(wrappers.at(3).html()).to.equal('<div>baz</div>')
  })

  // This case is success.
  it('Vue.extend', () => {
    const C = Vue.extend(Component)
    Component1.clone = false
    const wrapper = mount(C, Component1)
    const wrappers = wrapper.findAll('div')

    expect(wrappers.at(0).html()).to.equal('<div><div>foo</div><div>bar</div><div>baz</div></div>')
    expect(wrappers.at(1).html()).to.equal('<div>foo</div>')
    expect(wrappers.at(2).html()).to.equal('<div>bar</div>')
    expect(wrappers.at(3).html()).to.equal('<div>baz</div>')
  })
})
```

**Comment by eddyerburgh** [comment] 2017-12-22 11:27
I identified and fixed 2 problems:

1) Extended uncompiled components weren't compiled
2) Extended components couldn't be used as selectors in `find`/`findAll`

I fixed both these issues, but have been unable to reproduce the original error message. Can you provide minimal reproduction?

**Comment by eddyerburgh** [comment] 2018-01-10 06:42
Hi @sygrinberg . This has been released in beta.9.

Is your original problem fixed with this release?

**Comment by eddyerburgh** [comment] 2018-01-27 07:27
I believe this has been fixed. If anyone has any future issues with extended, please create an issue with a reproduction

**Closed by eddyerburgh** 2018-01-27 07:27 UTC
Labels: bug
