### ISSUE TITLE
Updated method not called

### ISSUE THREAD

**Issue by tangjinzhou** [vuejs/vue-test-utils#624] opened 2018-05-18 03:37 UTC
### Version
1.0.0-beta.16

### Reproduction link
[https://github.com/vueComponent/ant-design](https://github.com/vueComponent/ant-design)

### Steps to reproduce
* npm i
* npm run test

### What is expected?
After `setProps`, `updated` method called at [Modal.test.js](https://github.com/vueComponent/ant-design/blob/master/components/modal/__tests__/Modal.test.js)

### What is actually happening?
After `setProps`, `updated` method not called at [Modal.test.js](https://github.com/vueComponent/ant-design/blob/master/components/modal/__tests__/Modal.test.js)

**Comment by tangjinzhou** [comment] 2018-05-18 03:38
https://github.com/vueComponent/ant-design/blob/master/components/modal/__tests__/Modal.test.js

**Comment by eddyerburgh** [comment] 2018-05-18 06:12
Thanks, this is a duplicate of https://github.com/vuejs/vue-test-utils/issues/455.

The reason for this is that we now set the instance watcher to `sync`, which means the update event is never fired. This is a serious issue that I'm investigating, but it won't have a quick fix. For the moment, you will need to test by setting `sync` to false and using Vue.nextTick:

```js
it('calls onUpdate when component updates', (done) => {
  const onUpdate = jest.fn()

  const wrapper = mount(TestComponent, {
    sync: false,
    propsData: {
      onUpdate
    }
  })

  Vue.nextTick(() => {
    expect(onUpdate).toHaveBeenCalled()
    done()
  })
})
```

I'm closing in favor of the existing issue.

**Closed as completed** 2018-05-18 06:14 UTC
